"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
import type {ProjectRecord} from "@/data/projects";
import {recurringFrequencies,recurringFunds,type RecurringFrequency} from "@/data/recurring";
type Destination={id:string;title:string;region:string;description:string;kind:"fund"|"project";slug?:string;proofStatus:string};
const labels:Record<RecurringFrequency,string>={daily:"يومي",friday:"كل جمعة",monthly:"شهري"};
const focusable='a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
function estimate(f:RecurringFrequency,a:number){return f==="daily"?{monthly:a*30,annual:a*365}:f==="friday"?{monthly:a*4.33,annual:a*52}:{monthly:a,annual:a*12}}
export function RecurringPlanBuilder({projects}:{projects:ProjectRecord[]}){
 const destinations=useMemo<Destination[]>(()=>[...recurringFunds.map(x=>({...x,kind:"fund" as const})),...projects.map(p=>({id:p.id,title:p.title.ar,region:p.region==="gaza"?"غزة":p.region==="al-quds"?"القدس":p.region==="al-aqsa"?"الأقصى":"مشروع رسمي",description:p.summary.ar,kind:"project" as const,slug:p.slug,proofStatus:p.image?"مصدر ميداني مؤقت متاح":"التوثيق قيد الاعتماد"}))],[projects]);
 const [frequency,setFrequency]=useState<RecurringFrequency>("friday"),[amount,setAmount]=useState(50),[custom,setCustom]=useState(""),[destinationId,setDestinationId]=useState("recurring-most-needed"),[start,setStart]=useState("after-confirmation"),[message,setMessage]=useState(""),[toast,setToast]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[step,setStep]=useState(1);const sheetRef=useRef<HTMLElement|null>(null),triggerRef=useRef<HTMLButtonElement|null>(null);
 const freq=recurringFrequencies.find(x=>x.id===frequency)!;const selected=custom?Number(custom):amount;const destination=destinations.find(x=>x.id===destinationId);const valid=Boolean(destination)&&Number.isFinite(selected)&&selected>0;const estimates=estimate(frequency,valid?selected:0);
 useEffect(()=>{setCustom("");setAmount(recurringFrequencies.find(x=>x.id===frequency)!.amounts[frequency==="friday"?1:0])},[frequency]);
 useEffect(()=>{const h=(e:Event)=>{const id=(e as CustomEvent<{id:string}>).detail?.id;if(destinations.some(x=>x.id===id)){setDestinationId(id);document.getElementById("recurring-plan-builder")?.scrollIntoView({behavior:"smooth"})}};window.addEventListener("minber:select-recurring-destination",h);return()=>window.removeEventListener("minber:select-recurring-destination",h)},[destinations]);
 useEffect(()=>{if(!mobileOpen||!sheetRef.current)return;const dialog=sheetRef.current,old=document.body.style.overflow;document.body.style.overflow="hidden";const list=()=>Array.from(dialog.querySelectorAll<HTMLElement>(focusable));setTimeout(()=>list()[0]?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMobileOpen(false);return}if(e.key!=="Tab")return;const a=list();if(!a.length)return;const first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key);triggerRef.current?.focus()}},[mobileOpen]);
 const add=()=>{if(!valid||!destination)return;window.dispatchEvent(new CustomEvent("minber:add-to-basket",{detail:{intent:"recurring",intentLabel:"تبرع مستمر",donationMode:"recurring",frequency:labels[frequency],amount:selected,currency:"USD",fundId:destination.kind==="fund"?destination.id:undefined,projectId:destination.kind==="project"?destination.id:undefined,slug:destination.slug,project:destination.title,startPreference:start,estimatedMonthly:Number(estimates.monthly.toFixed(2)),estimatedAnnual:Number(estimates.annual.toFixed(2)),source:"recurring-page",receiptType:"recurring"}}));setToast(true);setMessage("تمت إضافة الخطة التجريبية إلى سلة العطاء.");setTimeout(()=>setToast(false),2200)};
 const frequencyField=<fieldset><legend>1. اختر الدورية</legend><div className="recurring-choice-grid">{recurringFrequencies.map(x=><button type="button" key={x.id} aria-pressed={frequency===x.id} className={frequency===x.id?"is-selected":""} onClick={()=>setFrequency(x.id)}><strong>{x.label}</strong><small>{x.description}</small></button>)}</div></fieldset>;
 const destinationField=<fieldset><legend>2. اختر جهة العطاء</legend><div className="recurring-destinations">{destinations.map(x=><button type="button" key={x.id} aria-pressed={destinationId===x.id} className={destinationId===x.id?"is-selected":""} onClick={()=>setDestinationId(x.id)}><span>{x.kind==="fund"?"صندوق عام":"مشروع رسمي"}</span><strong>{x.title}</strong><small>{x.region} · {x.proofStatus}</small></button>)}</div></fieldset>;
 const amountField=<fieldset><legend>3. اختر المبلغ · USD</legend><small className="builder-label">مبالغ تجريبية لتصميم التجربة</small><div className="recurring-amount-grid">{freq.amounts.map(x=><button type="button" key={x} aria-pressed={!custom&&amount===x} className={!custom&&amount===x?"is-selected":""} onClick={()=>{setAmount(x);setCustom("")}}>{x} USD</button>)}</div><label className="recurring-custom"><span>مبلغ آخر</span><input inputMode="decimal" value={custom} onChange={e=>setCustom(e.target.value.replace(/[^0-9.]/g,""))} aria-invalid={Boolean(custom)&&!valid} aria-describedby="recurring-amount-error"/><b>USD</b></label>{Boolean(custom)&&!valid&&<small id="recurring-amount-error" className="field-error">أدخل مبلغًا موجبًا صالحًا.</small>}</fieldset>;
 const startField=<fieldset><legend>4. بداية الخطة</legend><div className="recurring-start-options">{[["after-confirmation","تبدأ بعد التأكيد"],["next-month","بداية الشهر القادم"]].map(([id,label])=><button type="button" key={id} aria-pressed={start===id} className={start===id?"is-selected":""} onClick={()=>setStart(id)}>{label}</button>)}</div><p className="builder-help">سيظهر موعد الخصم القادم بوضوح قبل التأكيد في التجربة الكاملة.</p></fieldset>;
 const summary=<aside className="recurring-plan-summary" aria-live="polite"><span>ملخص خطتك</span><dl><div><dt>الدورية</dt><dd>{labels[frequency]}</dd></div><div><dt>المبلغ لكل عملية</dt><dd>{valid?selected:0} USD</dd></div><div><dt>الجهة</dt><dd>{destination?.title||"اختر جهة"}</dd></div><div><dt>نوع الجهة</dt><dd>{destination?.kind==="fund"?"صندوق عام":"مشروع رسمي"}</dd></div><div><dt>بداية الخطة</dt><dd>{start==="after-confirmation"?"بعد التأكيد":"بداية الشهر القادم"}</dd></div><div><dt>التقدير الشهري</dt><dd>{estimates.monthly.toFixed(2)} USD تقريبًا</dd></div><div><dt>التقدير السنوي</dt><dd>{estimates.annual.toFixed(2)} USD تقريبًا</dd></div></dl><p>تقدير تقريبي؛ عدد العمليات الفعلي يعتمد على تاريخ بدء الخطة.</p>{message&&<p className="prototype-message" role="status">{message}</p>}<Button type="button" fullWidth onClick={()=>valid&&setMessage("سيتم الانتقال إلى Checkout وربط نظام الخصم المتكرر في المرحلة التشغيلية.")} disabled={!valid}>فعّل عطاءً مستمرًا</Button><Button type="button" variant="outline" fullWidth onClick={add} disabled={!valid}>أضف الخطة إلى سلة العطاء</Button></aside>;
 return <><div className="recurring-builder-desktop"><div className="recurring-builder-fields">{frequencyField}{destinationField}{amountField}{startField}</div>{summary}</div><div className="recurring-builder-mobile"><div className="recurring-mobile-step"><span>الخطوة {step} من 5</span>{step===1?frequencyField:step===2?destinationField:step===3?amountField:step===4?startField:summary}</div><div className="recurring-mobile-step-actions"><Button type="button" variant="outline" disabled={step===1} onClick={()=>setStep(x=>Math.max(1,x-1))}>السابق</Button><Button type="button" disabled={step===5} onClick={()=>setStep(x=>Math.min(5,x+1))}>التالي</Button></div></div><div className="recurring-context-bar"><div><small>{labels[frequency]}</small><strong>{valid?`${selected} USD`:"اختر مبلغًا"}</strong></div><button ref={triggerRef} type="button" onClick={()=>setMobileOpen(true)}>راجع خطتك</button></div>{mobileOpen&&<div className="recurring-sheet-layer"><button className="recurring-sheet-backdrop" type="button" onClick={()=>setMobileOpen(false)} aria-label="إغلاق مراجعة الخطة"/><aside ref={sheetRef} className="recurring-sheet" role="dialog" aria-modal="true" aria-labelledby="recurring-sheet-title"><header><div><span>خطة عطاء مستمر</span><h2 id="recurring-sheet-title">راجع خطتك</h2></div><button type="button" onClick={()=>setMobileOpen(false)} aria-label="إغلاق">×</button></header><div className="recurring-sheet-scroll">{frequencyField}{destinationField}{amountField}{startField}{summary}</div></aside></div>}<div className={toast?"toast is-visible":"toast"} role="status" aria-live="polite">تمت إضافة خطة العطاء إلى السلة</div></>;
}
export function RecurringProjectSelectButton({id}:{id:string}){return <Button type="button" variant="outline" size="small" onClick={()=>window.dispatchEvent(new CustomEvent("minber:select-recurring-destination",{detail:{id}}))}>اختر لهذا العطاء</Button>}
export function RecurringManagementPreview(){const [status,setStatus]=useState<"active"|"paused"|"ended">("active"),[notice,setNotice]=useState("");const text={active:"نشطة",paused:"متوقفة مؤقتًا",ended:"منتهية"}[status];return <div className="recurring-management-card"><div className="management-heading"><div><span>معاينة حساب المتبرع</span><h3>خطة حيث الحاجة أشد</h3></div><b data-status={status}>● {text}</b></div><dl><div><dt>الدورية</dt><dd>كل جمعة</dd></div><div><dt>المبلغ</dt><dd>50 USD</dd></div><div><dt>الوجهة</dt><dd>حيث الحاجة أشد</dd></div><div><dt>العملية القادمة</dt><dd>سيظهر بعد ربط نظام الدفع</dd></div></dl><div className="management-actions"><button type="button" onClick={()=>setNotice("معاينة تعديل المبلغ فقط — لا يوجد حفظ حقيقي.")}>تعديل المبلغ</button><button type="button" onClick={()=>setNotice("معاينة تغيير الجهة فقط — لا يوجد حفظ حقيقي.")}>تغيير الجهة</button><button type="button" onClick={()=>{setStatus("paused");setNotice("تم عرض حالة الإيقاف المؤقت تجريبيًا.")}}>إيقاف مؤقت</button><button type="button" onClick={()=>{setStatus("ended");setNotice("تم عرض حالة إنهاء الخطة تجريبيًا.")}}>إنهاء الخطة</button><button type="button" onClick={()=>{setStatus("active");setNotice("تمت استعادة الحالة النشطة في المعاينة.")}}>إعادة التنشيط</button></div>{notice&&<p role="status">{notice}</p>}</div>}
