import {Button} from "@/components/ui/button";
import {ProjectFaq} from "@/components/project-detail/project-faq";
import {RecurringManagementPreview,RecurringPlanBuilder,RecurringProjectSelectButton} from "./recurring-plan-builder";
import {recurringFaq,recurringHowItWorks,recurringImpactSteps,recurringRhythm} from "@/data/recurring";
import type {ProjectRecord} from "@/data/projects";
const region=(v:string)=>v==="gaza"?"غزة":v==="al-quds"?"القدس":v==="al-aqsa"?"الأقصى":"مشروع رسمي";
export function RecurringExperience({projects}:{projects:ProjectRecord[]}){return <main id="main-content" className="recurring-page"><div className="site-container"><nav className="recurring-breadcrumb" aria-label="مسار التنقل"><a href="/">الرئيسية</a><span aria-hidden="true">←</span><span aria-current="page">التبرع المستمر</span></nav></div>
<section className="recurring-hero"><div className="site-container recurring-hero-grid"><div><span className="recurring-eyebrow">عطاء يتجدد</span><h1>عطاء صغير يتكرر<br/>وأثر يبقى حاضرًا</h1><p>اختر مبلغًا ودورية تناسبك، ووجّه عطاءك إلى القدس أو غزة أو حيث الحاجة أشد، مع إمكانية التعديل أو الإيقاف مستقبلًا.</p><div className="recurring-hero-actions"><Button href="#recurring-plan-builder" size="large">ابدأ عطاءً مستمرًا</Button><Button href="#recurring-projects" variant="outline" size="large">استكشف المشاريع المؤهلة</Button></div><ul><li>يمكن التعديل مستقبلًا</li><li>يمكن الإيقاف مستقبلًا</li><li>إيصال مع كل عملية</li><li>تحديثات أثر متتابعة</li></ul><small>هذه تجربة Frontend ولا يتم تنفيذ خصم متكرر حقيقي.</small></div><div className="recurring-hero-visual"><div role="img" aria-label="صورة ميدانية مطلوبة للعطاء المستمر"><strong>APPROVED RECURRING GIVING IMAGE REQUIRED</strong><span>Real recurring humanitarian activity · Al-Quds or Gaza · Verified source · No AI · No banking imagery</span></div><ol><li>العطاء</li><li>التنفيذ</li><li>التحديث</li><li>أثر جديد</li></ol></div></div></section>
<section className="recurring-rhythm" aria-label="مسار العطاء المستمر"><div className="site-container">{recurringRhythm.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong>{i<recurringRhythm.length-1&&<b aria-hidden="true">←</b>}</div>)}</div></section>
<section id="recurring-plan-builder" className="recurring-section recurring-builder-section"><div className="site-container"><div className="recurring-section-heading"><span>خطتك المرنة</span><h2>أنشئ خطة عطائك المستمر</h2><p>اختر الدورية والوجهة والمبلغ، ثم راجع التقدير الشهري والسنوي قبل الإضافة إلى السلة.</p></div><RecurringPlanBuilder projects={projects}/></div></section>
<section className="recurring-section recurring-impact"><div className="site-container"><div className="recurring-section-heading"><span>استمرارية موثقة</span><h2>أثر يتجدد مع كل عملية</h2></div><ol>{recurringImpactSteps.map(([title,text],i)=><li key={title}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></div></section>
<section id="recurring-projects" className="recurring-section recurring-projects"><div className="site-container"><div className="recurring-section-heading"><span>مشاريع رسمية</span><h2>مشاريع تقبل العطاء المستمر</h2><p>هذه القائمة مشتقة مباشرة من أهلية recurring في بيانات المشاريع.</p></div><div className="recurring-project-grid">{projects.slice(0,3).map(p=><article key={p.id}>{p.image?<img src={p.image.sourceUrl} alt={p.image.alt.ar}/>:<div className="recurring-project-placeholder">APPROVED PROJECT IMAGE REQUIRED</div>}<div><small>{region(p.region)} · {p.status==="active"?"نشط":"قيد المراجعة"}</small><h3>{p.title.ar}</h3><p>{p.summary.ar}</p><span>{p.image?"مصدر ميداني مؤقت متاح":"Proof status: قيد الاعتماد"}</span><div><Button href={`/projects/${p.slug}`} variant="text" size="small">عرض المشروع</Button><RecurringProjectSelectButton id={p.id}/></div></div></article>)}</div></div></section>
<section className="recurring-section recurring-how"><div className="site-container"><div className="recurring-section-heading"><span>خطوات واضحة</span><h2>كيف يعمل عطاؤك المستمر؟</h2></div><ol>{recurringHowItWorks.map((x,i)=><li key={x}><b>{i+1}</b><span>{x}</span></li>)}</ol><p>تنفيذ العمليات والتعديل والإيقاف يحتاجان ربطًا بالنظام التشغيلي وحساب المتبرع.</p></div></section>
<section className="recurring-section recurring-management"><div className="site-container recurring-two-column"><div><div className="recurring-section-heading"><span>إدارة مستقبلية</span><h2>تحكّم بخطتك مستقبلًا</h2><p>معاينة بصرية لخطة واحدة، وليست حساب متبرع أو Dashboard كاملة.</p></div><RecurringManagementPreview/></div><div className="recurring-receipt-stack"><article className="recurring-receipt"><small>معاينة تصميمية فقط</small><div>OFFICIAL LOGO REQUIRED</div><h3>إيصال عملية متكررة</h3><dl><div><dt>النوع</dt><dd>تبرع مستمر</dd></div><div><dt>المبلغ</dt><dd>50 USD</dd></div><div><dt>الدورية</dt><dd>كل جمعة</dd></div><div><dt>الجهة</dt><dd>حيث الحاجة أشد</dd></div></dl><code>PREVIEW-RECURRING-0001</code></article><article className="recurring-impact-summary"><small>ملخص أثر دوري</small><h3>أثر عطائك مع الوقت</h3><dl><div><dt>عدد العمليات</dt><dd>DATA REQUIRED</dd></div><div><dt>إجمالي المساهمة</dt><dd>DATA REQUIRED</dd></div><div><dt>آخر تحديث</dt><dd>DATA REQUIRED</dd></div><div><dt>التقرير</dt><dd>سيُضاف لاحقًا</dd></div></dl></article></div></div></section>
<section className="recurring-section recurring-flexibility"><div className="site-container"><div className="recurring-section-heading"><span>ثقة ومرونة</span><h2>مرونة واضحة دون التزام مخفي</h2></div><div>{["ترى قيمة كل عملية قبل التأكيد.","ترى الدورية بوضوح.","يمكن تعديل الخطة مستقبلًا.","يمكن إيقافها مستقبلًا.","لا يتم تغيير المبلغ دون موافقتك.","الإيصالات والتحديثات تبقى مرتبطة بالخطة."].map(x=><p key={x}>✓ {x}</p>)}</div><small>تفاصيل الإلغاء والاسترداد والدفع المتكرر تحتاج اعتماد السياسة التشغيلية والقانونية.</small></div></section>
<section className="recurring-section recurring-faq"><div className="site-container"><div className="recurring-section-heading"><span>قبل البدء</span><h2>الأسئلة الشائعة</h2></div><ProjectFaq items={recurringFaq}/></div></section>
<section className="recurring-final"><div className="site-container"><div><span>ابدأ بخطوة بسيطة</span><h2>ابدأ بخطة تناسبك<br/>ودع أثرها يستمر</h2></div><div><Button href="#recurring-plan-builder" size="large">أنشئ خطة عطاء</Button><Button href="/#donate" variant="outline" size="large">تبرع لمرة واحدة</Button></div></div></section></main>}
