"use client";

import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Check, ChevronDown, ChevronUp, Clipboard, Download, Info, Lightbulb, Loader2, Plus, Search, Send, Trash2, WandSparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { SupportedLocale } from "@/lib/locales";
import { Textarea } from "@/components/ui/textarea";

type SeoContentType = "campaign" | "category" | "blog";
/**
 * Every publicly routed locale. Derived from the single source of truth rather
 * than listed here, so promoting a locale cannot leave this behind — which is
 * exactly what happened when the Minbar port took the site from 8 to 19.
 */
type LocaleCode = SupportedLocale;
type FaqItem = { question: string; answer: string };
type SeoDraft = { seoTitle: string; metaDescription: string; primaryKeyword: string; keywords: string[]; longTailKeywords: string[]; altText: string; faq: FaqItem[]; schemaType: string; notes: string[] };
type Props = { type: SeoContentType; locale?: LocaleCode; title?: string | null; description?: string | null; slug?: string | null; imageCount?: number };
type SeoAssistantPayload = Partial<SeoDraft> & { source?: string; type?: SeoContentType; locale?: LocaleCode; suggestedSlug?: string; improvedText?: string; sentAt?: string };

/** Display names for the locales this card has authored copy for. Partial by
 * design — `fallbackDraft` falls back to Arabic for anything absent, which is
 * better than shipping placeholder SEO copy in a language nobody wrote. */
const LOCALE_NAMES: Partial<Record<LocaleCode, string>> = { ar: "العربية", en: "English", fr: "Français", tr: "Türkçe", id: "Bahasa", pt: "Português", es: "Español", de: "Deutsch" };
const STOP = new Set(["في","من","على","إلى","الى","عن","مع","هذا","هذه","ذلك","تلك","الذي","التي","كل","كما","أو","او","ثم","أن","ان","إن","هو","هي","هم","كان","كانت","يكون","تكون","لها","له","لهم","بين","بعد","قبل","خلال","ضمن","وقد","لقد","حيث","غير","أكثر","اكثر","the","and","for","with","this","that","from","about","your","you","are","our","can","will","let","them","their","by","into","type","text","content","paragraph","doc","hardbreak","attrs","marks","https","http","www"]);

type LocalizedSeoCopy = { blogSuffix: string; categorySuffix: string; campaignSuffix: string; emptyMeta: (title: string) => string; alt: (title: string) => string; longTailBlog: (primary: string) => string[]; longTailFundraising: (primary: string) => string[]; faqBlog: (primary: string) => FaqItem[]; faqFundraising: (primary: string) => FaqItem[] };
/** Arabic is guaranteed so `fallbackDraft` always has a base to fall back to;
 * the rest are optional because only some locales have authored copy. */
const localizedCopy: { ar: LocalizedSeoCopy } & Partial<Record<LocaleCode, LocalizedSeoCopy>> = {
  ar: { blogSuffix: "دليل مختصر", categorySuffix: "مشاريع تبرع موثوقة", campaignSuffix: "تبرع آمن", emptyMeta: (title) => `تعرف على ${title} وساهم في دعم المحتاجين من خلال تبرع آمن وموثوق.`, alt: (title) => `${title} - صورة توضيحية للمبادرة الإنسانية`, longTailBlog: (p) => [`ما أهمية ${p}؟`, `كيف يساهم ${p} في دعم المحتاجين؟`, `أفضل طرق دعم ${p}`], longTailFundraising: (p) => [`تبرع لمشروع ${p}`, `كيف أساهم في ${p}؟`, `${p} للأسر المحتاجة`, `دعم ${p} أونلاين`], faqBlog: (p) => [{ question: `ما أهمية ${p || "هذا الموضوع"}؟`, answer: "يساعد هذا المحتوى القارئ على فهم الموضوع وأثره الإنساني بطريقة واضحة." }, { question: "كيف يمكن دعم المبادرات الإنسانية؟", answer: "يمكن دعم المبادرات عبر التبرع الآمن أو مشاركة المحتوى مع المهتمين." }, { question: "لماذا تُعد الشفافية مهمة؟", answer: "الشفافية تساعد المتبرع على فهم أثر مساهمته وكيف تصل للمستفيدين." }], faqFundraising: (p) => [{ question: `ما هو ${p || "هذا المشروع"}؟`, answer: "مبادرة إنسانية تهدف إلى دعم المحتاجين وتوفير احتياج واضح بطريقة منظمة." }, { question: `كيف أساهم في ${p || "هذا المشروع"}؟`, answer: "يمكنك المساهمة عبر اختيار قيمة التبرع المناسبة وإتمام التبرع بأمان من خلال الموقع." }, { question: "من المستفيد من التبرع؟", answer: "تُوجّه التبرعات إلى المستحقين حسب طبيعة المشروع والمنطقة المستهدفة." }] },
  en: { blogSuffix: "Short Guide", categorySuffix: "Trusted Donation Projects", campaignSuffix: "Secure Donation", emptyMeta: (title) => `Learn about ${title} and support people in need through a secure and trusted donation.`, alt: (title) => `${title} - humanitarian initiative image`, longTailBlog: (p) => [`Why ${p} matters`, `How ${p} helps people in need`, `Best ways to support ${p}`], longTailFundraising: (p) => [`Donate to ${p}`, `How to support ${p}`, `${p} for families in need`, `Support ${p} online`], faqBlog: (p) => [{ question: `Why is ${p || "this topic"} important?`, answer: "It helps readers understand the issue and its humanitarian impact clearly." }, { question: "How can humanitarian initiatives be supported?", answer: "They can be supported through secure donations or by sharing the content with interested people." }, { question: "Why is transparency important?", answer: "Transparency helps donors understand the impact of their contribution and how aid reaches beneficiaries." }], faqFundraising: (p) => [{ question: `What is ${p || "this project"}?`, answer: "A humanitarian initiative designed to support people in need in an organized and trustworthy way." }, { question: `How can I contribute to ${p || "this project"}?`, answer: "You can choose a suitable donation amount and complete your donation securely through the website." }, { question: "Who benefits from the donation?", answer: "Donations are directed to eligible beneficiaries according to the project type and target region." }] },
  fr: { blogSuffix: "Guide court", categorySuffix: "Projets de don fiables", campaignSuffix: "Don sécurisé", emptyMeta: (title) => `Découvrez ${title} et soutenez les personnes dans le besoin grâce à un don sécurisé et fiable.`, alt: (title) => `${title} - image d'initiative humanitaire`, longTailBlog: (p) => [`Pourquoi ${p} est important`, `Comment ${p} aide les personnes dans le besoin`, `Meilleures façons de soutenir ${p}`], longTailFundraising: (p) => [`Faire un don pour ${p}`, `Comment soutenir ${p}`, `${p} pour les familles dans le besoin`, `Soutenir ${p} en ligne`], faqBlog: (p) => [{ question: `Pourquoi ${p || "ce sujet"} est-il important ?`, answer: "Ce contenu aide le lecteur à comprendre le sujet et son impact humanitaire." }, { question: "Comment soutenir les initiatives humanitaires ?", answer: "Par un don sécurisé ou en partageant le contenu avec les personnes intéressées." }, { question: "Pourquoi la transparence est-elle importante ?", answer: "Elle aide le donateur à comprendre l'impact de sa contribution." }], faqFundraising: (p) => [{ question: `Qu'est-ce que ${p || "ce projet"} ?`, answer: "Une initiative humanitaire destinée à soutenir les personnes dans le besoin de manière organisée." }, { question: `Comment contribuer à ${p || "ce projet"} ?`, answer: "Vous pouvez choisir un montant adapté et finaliser le don en toute sécurité." }, { question: "Qui bénéficie du don ?", answer: "Les dons sont orientés vers les bénéficiaires éligibles selon la nature du projet." }] },
  tr: { blogSuffix: "Kısa Rehber", categorySuffix: "Güvenilir Bağış Projeleri", campaignSuffix: "Güvenli Bağış", emptyMeta: (title) => `${title} hakkında bilgi alın ve güvenli bağışla ihtiyaç sahiplerine destek olun.`, alt: (title) => `${title} - insani yardım görseli`, longTailBlog: (p) => [`${p} neden önemlidir?`, `${p} ihtiyaç sahiplerine nasıl yardım eder?`, `${p} destekleme yolları`], longTailFundraising: (p) => [`${p} için bağış yap`, `${p} nasıl desteklenir?`, `İhtiyaç sahibi aileler için ${p}`, `${p} online destek`], faqBlog: (p) => [{ question: `${p || "Bu konu"} neden önemlidir?`, answer: "Okuyucunun konuyu ve insani etkisini açık şekilde anlamasına yardımcı olur." }, { question: "İnsani yardım çalışmaları nasıl desteklenir?", answer: "Güvenli bağış yaparak veya içeriği ilgili kişilerle paylaşarak destek olunabilir." }, { question: "Şeffaflık neden önemlidir?", answer: "Bağışçı, katkısının etkisini ve yardımın nasıl ulaştığını daha iyi anlar." }], faqFundraising: (p) => [{ question: `${p || "Bu proje"} nedir?`, answer: "İhtiyaç sahiplerini düzenli ve güvenilir şekilde desteklemeyi amaçlayan insani bir çalışmadır." }, { question: `${p || "Bu proje"} için nasıl bağış yapabilirim?`, answer: "Uygun bağış tutarını seçip web sitesi üzerinden güvenle tamamlayabilirsiniz." }, { question: "Bağıştan kimler yararlanır?", answer: "Bağışlar projenin türüne ve hedef bölgesine göre hak sahiplerine ulaştırılır." }] },
  id: { blogSuffix: "Panduan Singkat", categorySuffix: "Proyek Donasi Tepercaya", campaignSuffix: "Donasi Aman", emptyMeta: (title) => `Pelajari ${title} dan dukung masyarakat yang membutuhkan melalui donasi aman dan tepercaya.`, alt: (title) => `${title} - gambar inisiatif kemanusiaan`, longTailBlog: (p) => [`Mengapa ${p} penting`, `Bagaimana ${p} membantu yang membutuhkan`, `Cara terbaik mendukung ${p}`], longTailFundraising: (p) => [`Donasi untuk ${p}`, `Cara mendukung ${p}`, `${p} untuk keluarga membutuhkan`, `Dukung ${p} online`], faqBlog: (p) => [{ question: `Mengapa ${p || "topik ini"} penting?`, answer: "Konten ini membantu pembaca memahami isu dan dampak kemanusiaannya." }, { question: "Bagaimana mendukung inisiatif kemanusiaan?", answer: "Melalui donasi aman atau membagikan konten kepada orang yang peduli." }, { question: "Mengapa transparansi penting?", answer: "Transparansi membantu donatur memahami dampak kontribusinya." }], faqFundraising: (p) => [{ question: `Apa itu ${p || "proyek ini"}?`, answer: "Inisiatif kemanusiaan untuk mendukung masyarakat yang membutuhkan secara teratur." }, { question: `Bagaimana saya mendukung ${p || "proyek ini"}?`, answer: "Pilih nominal donasi yang sesuai dan selesaikan donasi dengan aman melalui situs." }, { question: "Siapa penerima manfaat donasi?", answer: "Donasi disalurkan kepada penerima yang berhak sesuai jenis proyek dan wilayah sasaran." }] },
  pt: { blogSuffix: "Guia rápido", categorySuffix: "Projetos de doação confiáveis", campaignSuffix: "Doação segura", emptyMeta: (title) => `Conheça ${title} e apoie pessoas necessitadas com uma doação segura e confiável.`, alt: (title) => `${title} - imagem de iniciativa humanitária`, longTailBlog: (p) => [`Por que ${p} é importante`, `Como ${p} ajuda pessoas necessitadas`, `Melhores formas de apoiar ${p}`], longTailFundraising: (p) => [`Doar para ${p}`, `Como apoiar ${p}`, `${p} para famílias necessitadas`, `Apoiar ${p} online`], faqBlog: (p) => [{ question: `Por que ${p || "este tema"} é importante?`, answer: "Ajuda o leitor a compreender o tema e seu impacto humanitário." }, { question: "Como apoiar iniciativas humanitárias?", answer: "Com uma doação segura ou compartilhando o conteúdo com pessoas interessadas." }, { question: "Por que a transparência é importante?", answer: "Ajuda o doador a entender o impacto da sua contribuição." }], faqFundraising: (p) => [{ question: `O que é ${p || "este projeto"}?`, answer: "Uma iniciativa humanitária para apoiar pessoas necessitadas de forma organizada." }, { question: `Como contribuir para ${p || "este projeto"}?`, answer: "Escolha um valor adequado e conclua a doação com segurança pelo site." }, { question: "Quem se beneficia da doação?", answer: "As doações são direcionadas aos beneficiários elegíveis conforme o tipo do projeto." }] },
  es: { blogSuffix: "Guía breve", categorySuffix: "Proyectos de donación confiables", campaignSuffix: "Donación segura", emptyMeta: (title) => `Conoce ${title} y apoya a personas necesitadas mediante una donación segura y confiable.`, alt: (title) => `${title} - imagen de iniciativa humanitaria`, longTailBlog: (p) => [`Por qué ${p} es importante`, `Cómo ${p} ayuda a quienes lo necesitan`, `Mejores formas de apoyar ${p}`], longTailFundraising: (p) => [`Donar a ${p}`, `Cómo apoyar ${p}`, `${p} para familias necesitadas`, `Apoyar ${p} en línea`], faqBlog: (p) => [{ question: `¿Por qué es importante ${p || "este tema"}?`, answer: "Ayuda al lector a comprender el tema y su impacto humanitario." }, { question: "¿Cómo apoyar iniciativas humanitarias?", answer: "Con una donación segura o compartiendo el contenido con personas interesadas." }, { question: "¿Por qué es importante la transparencia?", answer: "Ayuda al donante a entender el impacto de su contribución." }], faqFundraising: (p) => [{ question: `¿Qué es ${p || "este proyecto"}?`, answer: "Una iniciativa humanitaria para apoyar a personas necesitadas de forma organizada." }, { question: `¿Cómo contribuir a ${p || "este proyecto"}?`, answer: "Elige un monto adecuado y completa la donación de forma segura en el sitio." }, { question: "¿Quién se beneficia de la donación?", answer: "Las donaciones se dirigen a beneficiarios elegibles según el tipo de proyecto." }] },
  de: { blogSuffix: "Kurzer Leitfaden", categorySuffix: "Vertrauenswürdige Spendenprojekte", campaignSuffix: "Sichere Spende", emptyMeta: (title) => `Erfahren Sie mehr über ${title} und unterstützen Sie Bedürftige mit einer sicheren Spende.`, alt: (title) => `${title} - Bild einer humanitären Initiative`, longTailBlog: (p) => [`Warum ${p} wichtig ist`, `Wie ${p} Bedürftigen hilft`, `Beste Wege, ${p} zu unterstützen`], longTailFundraising: (p) => [`Für ${p} spenden`, `Wie man ${p} unterstützt`, `${p} für bedürftige Familien`, `${p} online unterstützen`], faqBlog: (p) => [{ question: `Warum ist ${p || "dieses Thema"} wichtig?`, answer: "Dieser Inhalt hilft, das Thema und seine humanitäre Wirkung klar zu verstehen." }, { question: "Wie kann man humanitäre Initiativen unterstützen?", answer: "Durch eine sichere Spende oder durch Teilen der Inhalte mit Interessierten." }, { question: "Warum ist Transparenz wichtig?", answer: "Transparenz hilft Spendern, die Wirkung ihres Beitrags zu verstehen." }], faqFundraising: (p) => [{ question: `Was ist ${p || "dieses Projekt"}?`, answer: "Eine humanitäre Initiative, die Bedürftige organisiert und verlässlich unterstützt." }, { question: `Wie kann ich ${p || "dieses Projekt"} unterstützen?`, answer: "Wählen Sie einen passenden Spendenbetrag und schließen Sie die Spende sicher ab." }, { question: "Wer profitiert von der Spende?", answer: "Spenden werden je nach Projektart und Zielregion an berechtigte Empfänger weitergeleitet." }] },
};

function extractNode(node: any): string { if (!node) return ""; if (typeof node === "string") return node; if (Array.isArray(node)) return node.map(extractNode).filter(Boolean).join("\n"); if (typeof node !== "object") return ""; const own = typeof node.text === "string" ? node.text : ""; const children = Array.isArray(node.content) ? node.content.map(extractNode).filter(Boolean).join("\n") : ""; if (node.type === "hardBreak") return "\n"; return [own, children].filter(Boolean).join(node.type === "paragraph" ? "" : "\n").trim(); }
function clean(value?: string | null) { const raw = (value || "").trim(); if (!raw) return ""; const parse = (s: string) => { try { const json = JSON.parse(s.trim()); if (json?.type === "doc" || Array.isArray(json?.content)) return extractNode(json); } catch {} return ""; }; const direct = parse(raw); if (direct) return direct.replace(/\s+/g, " ").trim(); return raw.replace(/\\n/g, "\n").split(/\n+/).map((part) => { const embeddedStart = part.indexOf('{"type":"doc"'); if (embeddedStart >= 0) { const embedded = part.slice(embeddedStart, part.lastIndexOf("}") + 1); return [part.slice(0, embeddedStart), parse(embedded)].join(" "); } return part; }).join(" ").replace(/<[^>]+>/g, " ").replace(/https?:\/\/\S+/gi, " ").replace(/\bwww\.\S+/gi, " ").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim(); }
function tokens(text: string) { return text.replace(/[\u064B-\u065F]/g, "").replace(/[،؛؟!.,:()\[\]{}"'\\/]/g, " ").split(/\s+/).map((w) => w.trim()).filter((w) => { const l = w.toLowerCase(); if (w.length < 3 || STOP.has(l) || /^https?$/.test(l) || /^www/.test(l)) return false; return true; }); }
function topKeywords(title: string, body: string) { const m = new Map<string, number>(); tokens(`${title} ${title} ${body}`).forEach((w) => m.set(w, (m.get(w) || 0) + 1)); return [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10).map(([w]) => w); }
function schemaLabel(type: SeoContentType) { return type === "blog" ? "Article + FAQ" : type === "category" ? "CollectionPage + Breadcrumb" : "Fundraising Campaign + FAQ"; }
function scoreTone(score: number) { if (score >= 90) return { label: "ممتاز", cls: "border-emerald-200 bg-emerald-50 text-emerald-700", bar: "bg-emerald-500" }; if (score >= 75) return { label: "جيد", cls: "border-blue-200 bg-blue-50 text-blue-700", bar: "bg-blue-500" }; if (score >= 50) return { label: "يحتاج تحسين", cls: "border-amber-200 bg-amber-50 text-amber-700", bar: "bg-amber-500" }; return { label: "ضعيف", cls: "border-red-200 bg-red-50 text-red-700", bar: "bg-red-500" }; }
function normalizeArray(value: unknown, max = 10) { return Array.isArray(value) ? value.map((x) => String(x || "").trim()).filter(Boolean).slice(0, max) : []; }
function normalizeFaq(value: unknown) { return Array.isArray(value) ? value.map((item) => ({ question: String((item as any)?.question || "").trim(), answer: String((item as any)?.answer || "").trim() })).filter((x) => x.question && x.answer).slice(0, 6) : []; }
function packageToDraft(payload: SeoAssistantPayload, activeDraft: SeoDraft): Partial<SeoDraft> { const keywords = normalizeArray(payload.keywords, 12); const longTail = normalizeArray(payload.longTailKeywords, 8); const faq = normalizeFaq(payload.faq); return { seoTitle: payload.seoTitle || activeDraft.seoTitle, metaDescription: payload.metaDescription || activeDraft.metaDescription, primaryKeyword: payload.primaryKeyword || activeDraft.primaryKeyword, keywords: keywords.length ? keywords : activeDraft.keywords, longTailKeywords: longTail.length ? longTail : activeDraft.longTailKeywords, faq: faq.length ? faq : activeDraft.faq, altText: payload.altText || activeDraft.altText, schemaType: payload.schemaType || activeDraft.schemaType, notes: ["تم استلام هذه المسودة من أداة تحسين النص.", ...(payload.notes || [])] }; }
function fallbackDraft(type: SeoContentType, locale: LocaleCode, title: string, body: string, keywords: string[]): SeoDraft { const copy = localizedCopy[locale] || localizedCopy.ar; const primary = keywords[0] || title.split(/\s+/).slice(0, 3).join(" ") || ""; const suffix = type === "blog" ? copy.blogSuffix : type === "category" ? copy.categorySuffix : copy.campaignSuffix; const seoTitle = title ? `${title} | ${suffix}`.slice(0, 72) : ""; const metaDescription = body ? body.slice(0, 155) : title ? copy.emptyMeta(title) : ""; const longTailKeywords = primary ? (type === "blog" ? copy.longTailBlog(primary) : copy.longTailFundraising(primary)) : []; const faq = type === "blog" ? copy.faqBlog(primary || title) : copy.faqFundraising(primary || title); return { seoTitle, metaDescription, primaryKeyword: primary, keywords, longTailKeywords, altText: title ? copy.alt(title) : copy.alt(type === "blog" ? copy.blogSuffix : copy.campaignSuffix), faq, schemaType: schemaLabel(type), notes: locale === "ar" ? [] : [`اللغة المحددة: ${LOCALE_NAMES[locale] ?? locale}`] }; }

export function SmartSeoWorkbenchCard({ type, locale = "ar", title, description, slug, imageCount = 0 }: Props) {
  const storageKey = `${type}:${locale}:${clean(title)}`;
  const syncStorageKey = `seo-assistant:${type}:${locale}`;
  // Collapsed by default — the user must click to expand. Subsequent
  // open()/close() interactions are preserved across re-renders of the same
  // (type, locale, title) key; only an explicit incoming AI package or
  // applyIncomingPackage force-opens the card again (see below).
  const [open, setOpen] = useState(false);
  const [suggestionsOpen, setSuggestionsOpen] = useState(true);
  const [draftOpen, setDraftOpen] = useState(false);
  const [drafts, setDrafts] = useState<Record<string, SeoDraft>>({});
  const [incomingPackage, setIncomingPackage] = useState<SeoAssistantPayload | null>(null);
  const [incomingApplied, setIncomingApplied] = useState(false);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [professionalReady, setProfessionalReady] = useState(false);

  const base = useMemo(() => { const cleanTitle = clean(title); const cleanDescription = clean(description); const keywords = topKeywords(cleanTitle, cleanDescription); const wordCount = tokens(cleanDescription).length; const hasCta = /تبرع|ساهم|ادعم|اكفل|شارك|ساعد|donate|support|spenden|bağış|donar/i.test(cleanDescription); const hasImpact = /يوفر|يساهم|يساعد|يهدف|يدعم|يصل|يخفف|يحمي|يرعى|support|help|provide/i.test(cleanDescription); const slugOk = Boolean(slug && slug.length <= 70 && /^[a-z0-9\-_/]+$/i.test(slug)); const checks = [{ label: "الاسم الظاهر", points: cleanTitle.length >= 3 && cleanTitle.length <= 90 ? 18 : cleanTitle ? 10 : 0, max: 18, note: cleanTitle ? `${cleanTitle} — لا يلزم أن يكون هو عنوان SEO.` : "الاسم أو العنوان غير موجود." }, { label: "الوصف والمحتوى", points: wordCount >= (type === "blog" ? 120 : 45) ? 22 : wordCount >= 25 ? 12 : 4, max: 22, note: `عدد الكلمات التقريبي: ${wordCount}.` }, { label: "الكلمة المفتاحية", points: keywords[0] ? 15 : 0, max: 15, note: keywords[0] ? `الكلمة الأقرب: ${keywords[0]}.` : "لم نستطع استخراج كلمة مفتاحية واضحة." }, { label: "نية الباحث", points: hasCta || type === "blog" ? 13 : 6, max: 13, note: hasCta ? "توجد دعوة واضحة للتفاعل أو التبرع." : "أضف دعوة واضحة مثل: تبرع الآن، ساهم، ادعم المشروع." }, { label: "الأثر والثقة", points: hasImpact ? 14 : 5, max: 14, note: hasImpact ? "النص يوضح الأثر بشكل جيد." : "أضف جملة توضح أثر التبرع ومن يستفيد." }, { label: "الرابط والصور", points: (slugOk || !slug) && imageCount > 0 ? 10 : imageCount > 0 ? 7 : 3, max: 10, note: imageCount > 0 ? `عدد الصور: ${imageCount}.` : "الصورة مهمة في SEO والمشاركة." }, { label: "FAQ وبيانات جوجل", points: 4, max: 8, note: "يمكن تحسين الظهور بإضافة أسئلة شائعة وبيانات منظمة لاحقًا." }]; const score = Math.min(100, checks.reduce((sum, i) => sum + i.points, 0)); return { cleanTitle, cleanDescription, keywords, checks, score }; }, [title, description, slug, imageCount, type]);

  const activeDraft = drafts[storageKey] || fallbackDraft(type, locale, base.cleanTitle, base.cleanDescription, base.keywords);
  const tone = scoreTone(base.score);
  const suggestionsCount = [activeDraft.seoTitle, activeDraft.metaDescription, activeDraft.altText, activeDraft.primaryKeyword, ...activeDraft.keywords, ...activeDraft.longTailKeywords, ...activeDraft.faq.map((x) => x.question)].filter(Boolean).length;
  const updateDraft = (patch: Partial<SeoDraft>) => setDrafts((prev) => ({ ...prev, [storageKey]: { ...activeDraft, ...patch } }));

  useEffect(() => { setSuggestionsOpen(true); }, [storageKey]);
  useEffect(() => { const loadStored = () => { try { const raw = window.localStorage.getItem(syncStorageKey); if (!raw) return; const parsed = JSON.parse(raw); if (parsed?.type === type && parsed?.locale === locale) setIncomingPackage(parsed); } catch {} }; loadStored(); const listener = (event: Event) => { const detail = (event as CustomEvent<SeoAssistantPayload>).detail; if (detail?.type === type && detail?.locale === locale) { setIncomingPackage(detail); setIncomingApplied(false); setOpen(true); } }; window.addEventListener("seo-assistant:structured-suggestions", listener); return () => window.removeEventListener("seo-assistant:structured-suggestions", listener); }, [syncStorageKey, type, locale]);

  const copyText = async (key: string, value: string) => { if (!value) return; await navigator.clipboard.writeText(value); setCopiedKey(key); window.setTimeout(() => setCopiedKey(null), 1500); };
  const json = JSON.stringify({ locale, type, ...activeDraft }, null, 2);
  const downloadJson = () => { const url = URL.createObjectURL(new Blob([json], { type: "application/json;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = `seo-${type}-${locale}.json`; a.click(); URL.revokeObjectURL(url); };
  const applyIncomingPackage = () => { if (!incomingPackage) return; updateDraft(packageToDraft(incomingPackage, activeDraft)); setIncomingApplied(true); setProfessionalReady(true); setSuggestionsOpen(true); setDraftOpen(true); setOpen(true); };

  const generateProfessionalSeo = async () => { setGenerating(true); setGenerationError(null); try { const response = await axios.post("/api/admin/seo/suggestions", { type, locale, title: base.cleanTitle, description: base.cleanDescription, keywords: base.keywords }); const s = response.data?.suggestion; if (s) { updateDraft({ seoTitle: s.seoTitle || activeDraft.seoTitle, metaDescription: s.metaDescription || activeDraft.metaDescription, primaryKeyword: s.primaryKeyword || activeDraft.primaryKeyword, keywords: s.keywords?.length ? s.keywords : activeDraft.keywords, longTailKeywords: s.longTailKeywords?.length ? s.longTailKeywords : activeDraft.longTailKeywords, altText: s.altText || activeDraft.altText, faq: s.faq?.length ? s.faq : activeDraft.faq, schemaType: s.schemaType || activeDraft.schemaType, notes: s.notes || [] }); setProfessionalReady(true); setSuggestionsOpen(true); setDraftOpen(true); } } catch (error: any) { setGenerationError(error?.response?.data?.error || "تعذر تجهيز اقتراحات SEO المتقدمة"); } finally { setGenerating(false); } };

  const updateFaq = (index: number, patch: Partial<FaqItem>) => updateDraft({ faq: activeDraft.faq.map((f, i) => i === index ? { ...f, ...patch } : f) });
  const addFaq = () => updateDraft({ faq: [...activeDraft.faq, { question: "", answer: "" }] });
  const removeFaq = (index: number) => updateDraft({ faq: activeDraft.faq.filter((_, i) => i !== index) });

  return (
    <Card className="border-blue-100 bg-gradient-to-br from-white to-sky-50/40 shadow-sm">
      <CardHeader className="pb-3"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-3"><div className="rounded-full bg-blue-100 p-2 text-brand"><Search className="h-5 w-5" /></div><div><CardTitle className="text-base sm:text-lg">SEO الذكي</CardTitle><p className="mt-1 text-sm text-muted-foreground">تحليل وتهيئة SEO مستقلة لهذه اللغة فقط.</p></div></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-3 py-1 text-sm font-bold ${tone.cls}`}>{base.score}/100 · {tone.label}</span><span className="inline-flex items-center gap-1 rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700"><Lightbulb className="h-3.5 w-3.5" />{suggestionsCount} اقتراح</span><span className="rounded-full border border-slate-200 bg-white px-3 py-1 text-xs text-slate-600">{LOCALE_NAMES[locale]}</span><Button type="button" variant="outline" size="sm" onClick={() => setOpen((v) => !v)} className="gap-2">{open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}{open ? "طي يدوي" : "فتح التحليل"}</Button></div></div></CardHeader>
      {open && <CardContent className="space-y-4">
        {incomingPackage && <div className="rounded-xl border border-purple-200 bg-purple-50/80 p-3"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex gap-2"><Send className="mt-0.5 h-4 w-4 text-purple-700" /><div><div className="text-sm font-bold text-purple-900">تم استلام حزمة من أداة تحسين النص</div><p className="mt-1 text-xs leading-5 text-purple-800">يمكنك تطبيق العنوان والوصف والكلمات المفتاحية والأسئلة الشائعة على مسودة SEO لهذه اللغة.</p></div></div><Button type="button" size="sm" onClick={applyIncomingPackage} className="gap-2 bg-purple-700 hover:bg-purple-800"><Check className="h-4 w-4" />{incomingApplied ? "تم التطبيق" : "تطبيق على مسودة SEO"}</Button></div></div>}
        <div className="rounded-xl border border-blue-100 bg-blue-50/70 p-3 text-sm text-blue-900"><div className="flex gap-2"><Info className="mt-0.5 h-4 w-4 shrink-0" /><p>العنوان والوصف هنا لمحركات البحث والمشاركة ولا يغيران الاسم الظاهر داخل الموقع. الاسم الحالي: <strong>{base.cleanTitle || "غير محدد"}</strong>.</p></div></div>
        <div className="rounded-xl border bg-white p-4"><div className="mb-3 flex items-center justify-between"><div><div className="text-sm font-semibold">التقييم العام</div><div className="text-xs text-muted-foreground">خاص باللغة الحالية فقط</div></div><span className={`rounded-full border px-3 py-1 text-sm font-bold ${tone.cls}`}>{base.score}/100</span></div><div className="h-2.5 rounded-full bg-slate-100"><div className={`h-2.5 rounded-full ${tone.bar}`} style={{ width: `${base.score}%` }} /></div></div>
        <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={generateProfessionalSeo} disabled={generating} className="gap-2 border-purple-300 text-purple-700 hover:bg-purple-50">{generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <WandSparkles className="h-4 w-4" />}تجهيز اقتراحات متقدمة</Button><Button type="button" variant="outline" size="sm" onClick={() => copyText("all", json)} className="gap-2"><Clipboard className="h-4 w-4" />{copiedKey === "all" ? "تم النسخ" : "نسخ المسودة"}</Button><Button type="button" variant="outline" size="sm" onClick={downloadJson} className="gap-2"><Download className="h-4 w-4" />تحميل JSON</Button>{professionalReady && <span className="inline-flex items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700"><Check className="h-3.5 w-3.5" />نسخة محسّنة جاهزة</span>}</div>
        {generationError && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{generationError}</div>}
        <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{base.checks.map((item) => <ScoreBox key={item.label} item={item} />)}</div>
        <Panel title="اقتراحات تحسين الظهور" open={suggestionsOpen} setOpen={setSuggestionsOpen}><div className="rounded-xl border bg-white p-3"><div className="mb-2 text-xs font-semibold text-muted-foreground">معاينة نتيجة البحث</div><div className="rounded-lg bg-slate-50 p-3"><div className="text-[13px] text-green-700">minberiaksa.org</div><div className="mt-1 text-base font-semibold text-blue-700">{activeDraft.seoTitle || base.cleanTitle || "عنوان SEO"}</div><p className="mt-1 text-sm leading-6 text-slate-600">{activeDraft.metaDescription || "وصف Meta المقترح سيظهر هنا."}</p></div></div><div className="grid gap-3 lg:grid-cols-2"><InfoBox label="الاسم الظاهر داخل الموقع" value={base.cleanTitle || "غير محدد"} /><InfoBox label="عنوان SEO مقترح" value={activeDraft.seoTitle} onCopy={() => copyText("title", activeDraft.seoTitle)} copied={copiedKey === "title"} /><InfoBox label="وصف Meta مقترح" value={activeDraft.metaDescription} onCopy={() => copyText("meta", activeDraft.metaDescription)} copied={copiedKey === "meta"} /><InfoBox label="نص بديل للصورة" value={activeDraft.altText} onCopy={() => copyText("alt", activeDraft.altText)} copied={copiedKey === "alt"} /></div><div className="rounded-lg bg-slate-50 p-3"><div className="text-xs font-semibold text-muted-foreground">كلمات مفتاحية</div><div className="mt-2 flex flex-wrap gap-1.5">{activeDraft.keywords.map((kw) => <span key={kw} className="rounded-full border bg-white px-2 py-0.5 text-xs">{kw}</span>)}</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="text-xs font-semibold text-muted-foreground">عبارات بحث طويلة</div><div className="mt-2 grid gap-1 text-sm sm:grid-cols-2">{activeDraft.longTailKeywords.map((t) => <div key={t}>• {t}</div>)}</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="text-xs font-semibold text-muted-foreground">أسئلة شائعة مقترحة</div><div className="mt-2 grid gap-2 md:grid-cols-3">{activeDraft.faq.map((item) => <div key={item.question} className="rounded-md border bg-white p-2"><div className="text-xs font-semibold">{item.question}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.answer}</p></div>)}</div></div><InfoBox label="بيانات منظمة مقترحة لجوجل" value={activeDraft.schemaType} /></Panel>
        <Panel title="مسودة SEO قابلة للمراجعة" open={draftOpen} setOpen={setDraftOpen}><div className="grid gap-3 lg:grid-cols-2"><Field label="عنوان SEO" value={activeDraft.seoTitle} onChange={(v) => updateDraft({ seoTitle: v })} /><Field label="الكلمة الرئيسية" value={activeDraft.primaryKeyword} onChange={(v) => updateDraft({ primaryKeyword: v })} /><Field label="وصف Meta" value={activeDraft.metaDescription} onChange={(v) => updateDraft({ metaDescription: v })} area /><Field label="نص بديل للصورة" value={activeDraft.altText} onChange={(v) => updateDraft({ altText: v })} area /></div><div className="rounded-lg border bg-slate-50 p-3"><div className="mb-2 text-sm font-semibold">الكلمات المفتاحية</div><div className="grid gap-3 lg:grid-cols-2"><Field label="كلمات مفتاحية" value={activeDraft.keywords.join(", ")} onChange={(v) => updateDraft({ keywords: v.split(",").map((x) => x.trim()).filter(Boolean) })} area /><Field label="عبارات بحث طويلة" value={activeDraft.longTailKeywords.join("\n")} onChange={(v) => updateDraft({ longTailKeywords: v.split("\n").map((x) => x.trim()).filter(Boolean) })} area /></div></div><div className="rounded-lg border bg-slate-50 p-3"><div className="mb-3 flex items-center justify-between"><div className="text-sm font-semibold">الأسئلة الشائعة</div><Button type="button" variant="outline" size="sm" onClick={addFaq} className="gap-1"><Plus className="h-3.5 w-3.5" />إضافة سؤال</Button></div><div className="space-y-3">{activeDraft.faq.map((item, i) => <div key={i} className="rounded-md border bg-white p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold text-muted-foreground">سؤال {i + 1}</span><Button type="button" variant="ghost" size="sm" onClick={() => removeFaq(i)} className="h-7 gap-1 text-red-600"><Trash2 className="h-3.5 w-3.5" />حذف</Button></div><div className="grid gap-2 lg:grid-cols-2"><Input value={item.question} onChange={(e) => updateFaq(i, { question: e.target.value })} placeholder="السؤال" /><Textarea value={item.answer} onChange={(e) => updateFaq(i, { answer: e.target.value })} placeholder="الإجابة" className="min-h-[70px]" /></div></div>)}</div></div></Panel>
      </CardContent>}
    </Card>
  );
}

function Panel({ title, open, setOpen, children }: { title: string; open: boolean; setOpen: (value: boolean) => void; children: React.ReactNode }) { return <div className="rounded-xl border bg-white p-3"><button type="button" onClick={() => setOpen(!open)} className="flex w-full items-center justify-between text-right"><span className="flex items-center gap-2 text-sm font-semibold"><Lightbulb className="h-4 w-4 text-amber-600" />{title}</span>{open ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</button>{open && <div className="mt-3 space-y-3">{children}</div>}</div>; }
function ScoreBox({ item }: { item: { label: string; points: number; max: number; note: string } }) { const p = Math.round((item.points / item.max) * 100); const tone = p >= 85 ? "text-emerald-700 bg-emerald-500" : p >= 60 ? "text-blue-700 bg-blue-500" : p >= 35 ? "text-amber-700 bg-amber-500" : "text-red-700 bg-red-500"; const [text, bg] = tone.split(" "); return <div className="rounded-lg border bg-white p-3"><div className="flex items-center justify-between"><span className="text-sm font-medium">{item.label}</span><span className={`text-xs font-bold ${text}`}>{p}% · {item.points}/{item.max}</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className={`h-1.5 rounded-full ${bg}`} style={{ width: `${p}%` }} /></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.note}</p></div>; }
function InfoBox({ label, value, onCopy, copied }: { label: string; value: string; onCopy?: () => void; copied?: boolean }) { return <div className="rounded-lg bg-slate-50 p-3"><div className="mb-1 flex items-center justify-between"><div className="text-xs font-semibold text-muted-foreground">{label}</div>{onCopy && <button type="button" onClick={onCopy} className="inline-flex items-center gap-1 rounded-md border bg-white px-2 py-1 text-[11px] text-slate-600">{copied ? <Check className="h-3.5 w-3.5" /> : <Clipboard className="h-3.5 w-3.5" />}{copied ? "تم النسخ" : "نسخ"}</button>}</div><p className="text-sm leading-6">{value || "—"}</p></div>; }
function Field({ label, value, onChange, area }: { label: string; value: string; onChange: (value: string) => void; area?: boolean }) { return <div className="space-y-1"><label className="text-xs font-semibold text-muted-foreground">{label}</label>{area ? <Textarea value={value} onChange={(e) => onChange(e.target.value)} className="min-h-[90px]" /> : <Input value={value} onChange={(e) => onChange(e.target.value)} />}</div>; }
