import type {
  BrandAsset,
  BrandColor,
  BrandFont,
  BrandGuideline,
  BrandMessageFramework,
  BrandProfile,
} from "./brand-types";

export const brandProfiles: BrandProfile[] = [
  {
    id: "brand_gozbebekleri",
    key: "gozbebekleri",
    name: "Gözbebekleri Derneği",
    description: "هوية الجمعية الخيرية التشغيلية الأساسية للوحة التحكم الحالية.",
    mission: "إيصال حملات إغاثة موثوقة مع دليل واضح للمتبرع وتحديثات ميدانية عملية.",
    vision: "رحلة تبرع يكون فيها كل تبرع سهل الإعطاء، سهل الثقة، ومرتبطًا بوضوح بالأثر.",
    contentVoice: "دافئ، موثوق، مباشر، مركّز على الإغاثة، وقائم على الدليل.",
    messagePhilosophy: "أبقِ المتبرع قريبًا من الميدان دون مبالغة؛ اعرض الدليل والإيصال والخطوة التالية بوضوح.",
    primaryLocale: "tr",
    supportedLocales: ["tr", "ar", "en"],
    website: "yedicihan.org",
    isActive: true,
    status: "FOUNDATION",
    verificationNote: "ملف اللوحة النشط؛ لا تزال ملفات الشعار/الأصول الرسمية بحاجة إلى تأكيد الرفع النهائي.",
  },
  {
    id: "brand_minber_aksa",
    key: "minber_aksa",
    name: "Minber-i Aksa Derneği",
    description: "هوية القدس والأقصى وغزة والزكاة والوقف والعطاء المتكرر.",
    mission: "دعم القدس والأقصى وغزة والزكاة والوقف والعطاء الموثّق ميدانيًا بتجربة متبرع متعددة اللغات فاخرة.",
    vision: "إظهار أثر المتبرع في القدس والأقصى وغزة عبر مشاريع وتقارير وإيصالات وشهادات رسمية.",
    contentVoice: "إسلامي عصري، مركّز على القدس، هادئ، جدير بالثقة، وعاجل فقط عندما يدعمه الدليل.",
    messagePhilosophy: "استخدم لغة رسمية، ودليلًا مرئيًا، ووضوحًا في الزكاة والوقف، وكرامة المتبرع في كل رسالة.",
    primaryLocale: "tr",
    supportedLocales: ["ar", "en", "fr", "tr", "id", "pt", "es", "de"],
    website: "minberiaksa.org",
    isActive: false,
    status: "FOUNDATION",
    verificationNote: "استخدم محتوى/وسائط الموقع الرسمي فقط عند بناء صفحات منبر الأقصى العامة.",
  },
  {
    id: "brand_burak",
    key: "burak",
    name: "Burak Derneği",
    description: "هوية خيرية ثانوية بنبرة حملات تركية أنعم.",
    mission: "توفير رحلات تبرع تركية واضحة لحملات الإغاثة والأضاحي.",
    vision: "تجربة تبرع هادئة وموثوقة مدعومة بدليل بعد التبرع وتحديثات بسيطة.",
    contentVoice: "ناعم، جدير بالثقة، بنبرة خيرية تركية، واضح وواقعي.",
    messagePhilosophy: "أبقِ نص التبرع عمليًا ومحليًا وقائمًا على الدليل دون مبالغة في الوعود.",
    primaryLocale: "tr",
    supportedLocales: ["tr"],
    website: "burakdernegi.org",
    isActive: false,
    status: "FOUNDATION",
    verificationNote: "بيانات التواصل والتواصل الاجتماعي تحتاج تحققًا رسميًا قبل الاستخدام العام في الإنتاج.",
  },
];

export const brandAssets: BrandAsset[] = [
  {
    id: "asset_goz_primary_logo",
    profileId: "brand_gozbebekleri",
    title: "الشعار الأساسي",
    type: "LOGO",
    format: "SVG",
    fileUrl: null,
    previewUrl: null,
    usage: "اللوحة الرئيسية وإيصالات التبرع وترويسات الحملات الرسمية.",
    locale: "all",
    notes: "بحاجة إلى تأكيد: ارفع ملف الشعار/المتجه المعتمد.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_goz_receipt_template",
    profileId: "brand_gozbebekleri",
    title: "قالب إيصال التبرع",
    type: "CERTIFICATE",
    format: "PDF",
    fileUrl: null,
    previewUrl: null,
    usage: "رحلة الإيصال والشكر والدليل بعد التبرع.",
    locale: "tr",
    notes: "بحاجة إلى تأكيد: اربط بقالب شهادة حقيقي.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_minber_waqf_certificate",
    profileId: "brand_minber_aksa",
    title: "توجيه شهادة الوقف",
    type: "CERTIFICATE",
    format: "PDF",
    fileUrl: null,
    previewUrl: null,
    usage: "معاينة شهادة تبرع وقف القدس والتحميل بعد التبرع.",
    locale: "all",
    notes: "بحاجة إلى تأكيد: استخدم تصميم شهادة منبر الأقصى الرسمي عند توفره.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_minber_pattern_edge",
    profileId: "brand_minber_aksa",
    title: "حافة زخرفية هندسية خفيفة",
    type: "TEMPLATE",
    format: "FIGMA",
    fileUrl: null,
    previewUrl: null,
    usage: "لمسة إسلامية ناعمة على حواف الشهادات أو فواصل الأقسام فقط، ولا توضع فوق النص أو النماذج.",
    locale: "all",
    notes: "بحاجة إلى تأكيد: مصدر التصميم قيد الإعداد.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
  {
    id: "asset_burak_intro",
    profileId: "brand_burak",
    title: "مقدمة/خاتمة فيديو (عنصر مؤقت)",
    type: "VIDEO_INTRO",
    format: "VIDEO",
    fileUrl: null,
    previewUrl: null,
    usage: "فيديوهات الأضاحي والدليل الميداني بعد الاعتماد الرسمي.",
    locale: "tr",
    notes: "بحاجة إلى تأكيد: ارفع عنصر الموشن النهائي.",
    downloadable: false,
    createdBy: "brand-foundation",
    status: "TO_VERIFY",
  },
];

export const brandColors: BrandColor[] = [
  { id: "color_goz_blue", profileId: "brand_gozbebekleri", name: "أزرق الثقة", hex: "#025EB8", rgb: "2, 94, 184", usage: "PRIMARY", description: "لون الهوية الأساسي ولون التمييز في اللوحة.", order: 1 },
  { id: "color_goz_navy", profileId: "brand_gozbebekleri", name: "كحلي داكن", hex: "#10212B", rgb: "16, 33, 43", usage: "TEXT", description: "العناوين ولوحات الثقة والأسطح الجادة في اللوحة.", order: 2 },
  { id: "color_goz_ivory", profileId: "brand_gozbebekleri", name: "خلفية دافئة", hex: "#FFFDF8", rgb: "255, 253, 248", usage: "BACKGROUND", description: "خلفية ناعمة لصفحات الهوية الموجهة للمتبرعين.", order: 3 },
  { id: "color_minber_trust_navy", profileId: "brand_minber_aksa", name: "كحلي الثقة", hex: "#10212B", rgb: "16, 33, 43", usage: "PRIMARY", description: "لون الثقة الأساسي لمنبر الأقصى.", order: 1 },
  { id: "color_minber_deep_navy", profileId: "brand_minber_aksa", name: "كحلي داكن", hex: "#132C38", rgb: "19, 44, 56", usage: "TEXT", description: "العناوين ولوحات الثقة العالية.", order: 2 },
  { id: "color_minber_gold", profileId: "brand_minber_aksa", name: "ذهبي الأقصى", hex: "#D39A27", rgb: "211, 154, 39", usage: "ACCENT", description: "لمسات الوقف والشهادات والأقصى.", order: 3 },
  { id: "color_minber_red", profileId: "brand_minber_aksa", name: "أحمر منبر", hex: "#A93428", rgb: "169, 52, 40", usage: "CTA", description: "إجراءات التبرع العاجلة والتأكيد على غزة.", order: 4 },
  { id: "color_minber_green", profileId: "brand_minber_aksa", name: "أخضر الزكاة", hex: "#1F7A4D", rgb: "31, 122, 77", usage: "STATUS", description: "أهلية الزكاة وإشارات العطاء الموثّق.", order: 5 },
  { id: "color_minber_ivory", profileId: "brand_minber_aksa", name: "عاجي فاتح", hex: "#FFFDF8", rgb: "255, 253, 248", usage: "BACKGROUND", description: "خلفية الصفحة الدافئة الأساسية.", order: 6 },
  { id: "color_minber_sand", profileId: "brand_minber_aksa", name: "رملي ناعم", hex: "#F7F2EA", rgb: "247, 242, 234", usage: "BACKGROUND", description: "خلفية القسم الثانوية.", order: 7 },
  { id: "color_minber_muted", profileId: "brand_minber_aksa", name: "نص هادئ", hex: "#52616B", rgb: "82, 97, 107", usage: "TEXT", description: "النصوص الداعمة الطويلة.", order: 8 },
  { id: "color_burak_teal", profileId: "brand_burak", name: "فيروزي بوراك", hex: "#025E73", rgb: "2, 94, 115", usage: "PRIMARY", description: "لون هوية بوراك الأساسي.", order: 1 },
  { id: "color_burak_soft", profileId: "brand_burak", name: "أزرق ناعم", hex: "#EAF6FA", rgb: "234, 246, 250", usage: "BACKGROUND", description: "خلفية الحملات الناعمة.", order: 2 },
];

export const brandFonts: BrandFont[] = [
  { id: "font_goz_ui", profileId: "brand_gozbebekleri", name: "System UI", usage: "واجهة اللوحة", fallback: "Inter, Arial, sans-serif", source: "system", notes: "مستقر لشاشات اللوحة الداخلية." },
  { id: "font_minber_ar", profileId: "brand_minber_aksa", name: "Noto Kufi Arabic", usage: "العناوين العربية", fallback: "Tajawal, Arial, sans-serif", source: "Google Fonts", notes: "بحاجة إلى تأكيد مقابل خطوط الموقع العام النهائية." },
  { id: "font_minber_latin", profileId: "brand_minber_aksa", name: "Poppins", usage: "العناوين اللاتينية وأزرار التبرع", fallback: "Inter, Arial, sans-serif", source: "Google Fonts", notes: "يصلح للإنجليزية والتركية والفرنسية والبرتغالية والإسبانية والألمانية والإندونيسية." },
  { id: "font_burak_ui", profileId: "brand_burak", name: "Inter", usage: "واجهة الحملات التركية", fallback: "Arial, sans-serif", source: "system/google", notes: "بحاجة إلى تأكيد مع نظام تصميم بوراك النهائي." },
];

export const brandGuidelines: BrandGuideline[] = [
  {
    id: "guide_goz_proof",
    profileId: "brand_gozbebekleri",
    section: "proof",
    title: "الدليل قبل الضغط",
    body: "يجب أن يعرض نص الحملة تحديثات ميدانية أو إيصالات أو دليلًا تشغيليًا قبل طلب مبلغ أعلى.",
    examples: ["الإيصال متاح بعد التبرع", "يُشارك التحديث الميداني بعد التوزيع"],
    order: 1,
  },
  {
    id: "guide_goz_dignity",
    profileId: "brand_gozbebekleri",
    section: "donor-dignity",
    title: "احترام كرامة المستفيد",
    body: "تجنّب اللغة التي تُهين متلقّي المساعدة. أظهر الحاجة باحترام مع خطوة تالية واضحة.",
    examples: ["ادعم أسرة بطرد غذائي موثّق", "لا تستخدم عبارات مبالغ فيها من الشفقة"],
    order: 2,
  },
  {
    id: "guide_minber_alquds",
    profileId: "brand_minber_aksa",
    section: "copy",
    title: "استخدام «القدس» في النص الإنجليزي",
    body: "استخدم Al-Quds في النص الإنجليزي للمتبرع. استخدم Jerusalem فقط عند وجود مصدر قانوني أو عنوان أو اقتباس رسمي يتطلب ذلك.",
    examples: ["أظهر أثرك في القدس والأقصى وغزة", "تجنّب الصياغة العامة للمدينة"],
    order: 1,
  },
  {
    id: "guide_minber_zakat",
    profileId: "brand_minber_aksa",
    section: "proof",
    title: "وضوح الزكاة",
    body: "يجب أن يوضّح نص الزكاة الأهلية، ومعالجة الإيصال المنفصل، وحالة ملاحظة الشيخ، وتوفر الدليل.",
    examples: ["صندوق مؤهل للزكاة", "إيصال زكاة منفصل", "ملاحظة الشيخ بحاجة إلى تأكيد"],
    order: 2,
  },
  {
    id: "guide_minber_waqf",
    profileId: "brand_minber_aksa",
    section: "voice",
    title: "الوقف يبقى دائمًا",
    body: "يجب أن تبدو رسائل الوقف فاخرة ودائمة وقائمة على الشهادة دون زخرفة مزدحمة.",
    examples: ["خصّص حصة الوقف هذه بالاسم", "معاينة الشهادة قبل الدفع"],
    order: 3,
  },
  {
    id: "guide_global_ai",
    profileId: "brand_gozbebekleri",
    section: "cta",
    title: "مخرجات الذكاء الاصطناعي مسودات فقط",
    body: "قد يقترح الذكاء الاصطناعي نصوصًا وترجمات وفحوص ضوابط، لكنه لا يستطيع النشر أو إرسال الرسائل أو تغيير الميزانيات أو اعتماد الأصول.",
    examples: ["مسودة فقط", "بحاجة إلى اعتماد بشري"],
    order: 3,
  },
];

export const brandMessageFrameworks: BrandMessageFramework[] = [
  {
    id: "framework_goz_friday",
    profileId: "brand_gozbebekleri",
    name: "رسائل الجمعة",
    type: "FRIDAY",
    locale: "tr",
    structure: ["دعاء قصير", "حاجة موثّقة", "إجراء التبرع", "إشارة الإيصال/الدليل"],
    sampleText: "Cuma iyiliğinizi bugün güvenli bağışla ulaştırın. Bağış sonrası makbuz ve güncelleme paylaşılır.",
    doList: ["اجعلها قصيرة", "اذكر الإيصال", "استخدم زر إجراء واحدًا"],
    dontList: ["لا تَعِد بنتائج محددة دون دليل", "لا تضغط بالشعور بالذنب"],
  },
  {
    id: "framework_goz_thank_you",
    profileId: "brand_gozbebekleri",
    name: "الشكر",
    type: "THANK_YOU",
    locale: "tr",
    structure: ["امتنان", "ملخص التبرع", "ملاحظة الإيصال", "التحديث التالي"],
    sampleText: "Bağışınız için teşekkür ederiz. Makbuzunuz hazır olduğunda paylaşılacak, saha güncellemesi ayrıca iletilecektir.",
    doList: ["أكّد الثقة", "اشرح خطوة الدليل التالية"],
    dontList: ["لا تضف طلبًا قويًا ثانيًا مباشرة"],
  },
  {
    id: "framework_minber_zakat",
    profileId: "brand_minber_aksa",
    name: "الزكاة",
    type: "ZAKAT",
    locale: "en",
    structure: ["الأهلية", "النية", "إيصال منفصل", "الدليل", "تبرّع"],
    sampleText: "Give zakat with clear intention, separated receipt handling, and field proof where available.",
    doList: ["اذكر معالجة الزكاة", "تجنّب ادعاءات علماء زائفة"],
    dontList: ["لا تختلق ادعاءات الأهلية", "لا تُخفِ ثغرات التحقق"],
  },
  {
    id: "framework_minber_waqf",
    profileId: "brand_minber_aksa",
    name: "الوقف",
    type: "WAQF",
    locale: "en",
    structure: ["أثر دائم", "إهداء", "شهادة", "تحديثات", "تبرّع"],
    sampleText: "Dedicate an Al-Quds waqf share by name and receive a certificate after donation.",
    doList: ["اعرض معاينة الشهادة", "اجعل الإهداء واضحًا"],
    dontList: ["لا تستخدم زخارف ثقيلة فوق النماذج", "لا تبالغ في الدوام دون تفاصيل المشروع"],
  },
  {
    id: "framework_minber_emergency",
    profileId: "brand_minber_aksa",
    name: "الطوارئ",
    type: "EMERGENCY",
    locale: "en",
    structure: ["أين", "ما المطلوب", "كيف يساعد التبرع", "الدليل/التحديث", "زر الإجراء"],
    sampleText: "Help deliver urgent aid to Gaza through official Minber projects with receipt and impact updates.",
    doList: ["اذكر المكان", "اجعل الإلحاح قائمًا على الدليل"],
    dontList: ["لا تختلق إحصاءات لحظية", "لا تستخدم صورًا غير موثّقة"],
  },
  {
    id: "framework_goz_reactivation",
    profileId: "brand_gozbebekleri",
    name: "إعادة تفعيل المتبرع",
    type: "DONOR_REACTIVATION",
    locale: "tr",
    structure: ["تقدير دافئ", "مشروع مناسب", "طلب بسيط", "احترام إلغاء الاشتراك"],
    sampleText: "Daha önceki desteğiniz için teşekkür ederiz. Dilerseniz bu ayki yardım çalışmasına güvenli bağışla katılabilirsiniz.",
    doList: ["احترم الدعم السابق", "اجعل إلغاء الاشتراك محترمًا"],
    dontList: ["لا تُخجل المتبرعين غير النشطين", "لا تُلمّح إلى الإلزام"],
  },
  {
    id: "framework_minber_ramadan",
    profileId: "brand_minber_aksa",
    name: "رمضان",
    type: "RAMADAN",
    locale: "en",
    structure: ["توقيت مبارك", "مشروع/صندوق", "وضوح الزكاة/الصدقة", "الإيصال", "زر الإجراء"],
    sampleText: "Give this Ramadan through official Minber projects for Al-Quds, Al-Aqsa and Gaza.",
    doList: ["ادعم الاتجاهين RTL/LTR", "اذكر الزكاة عند الاقتضاء"],
    dontList: ["لا تزدحم نموذج التبرع"],
  },
  {
    id: "framework_goz_general",
    profileId: "brand_gozbebekleri",
    name: "حملة عامة",
    type: "GENERAL",
    locale: "tr",
    structure: ["الحاجة", "إشارة الثقة", "المبلغ/الإجراء", "الدليل"],
    sampleText: "Bugün güvenli bağışla sahadaki çalışmaya destek olun. Makbuz ve güncelleme bağış sonrası paylaşılır.",
    doList: ["زر إجراء أساسي واحد", "سطر إيصال واضح"],
    dontList: ["لا تخلط حملات كثيرة في رسالة واحدة"],
  },
];
