"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Badge} from "./badge";import {Button} from "./button";import {BasketIcon,CloseIcon,MinusIcon,PlusIcon,TrashIcon} from "./icons";import {IconButton} from "./icon-button";
type BasketIntent="zakat"|"waqf"|"recurring"|"urgent"|"general";
type BasketItem={id:number;projectId?:string;fundId?:string;slug?:string;intent:BasketIntent;intentLabel:string;project:string;donationMode?:"one-time"|"recurring"|"gift";frequency?:string;amount:number;currency:"USD";source?:string;receiptType?:"zakat"|"recurring";waqfType?:string;ownerName?:string;certificateType?:"waqf";startPreference?:string;estimatedMonthly?:number;estimatedAnnual?:number};
type AddBasketDetail=Omit<BasketItem,"id">;const modeLabels={"one-time":"مرة واحدة",recurring:"عطاء مستمر",gift:"إهداء تبرع"} as const;
const initialItems:BasketItem[]=[{id:1,intent:"zakat",intentLabel:"زكاة",project:"زكاة لفلسطين",donationMode:"one-time",amount:120,currency:"USD",receiptType:"zakat"},{id:2,intent:"waqf",intentLabel:"وقف",project:"سهم وقفي للقدس",donationMode:"one-time",amount:250,currency:"USD",certificateType:"waqf"}];
export function BasketTrigger({compact=false}:{compact?:boolean}){const[open,setOpen]=useState(false),[items,setItems]=useState(initialItems);const closeRef=useRef<HTMLButtonElement>(null),triggerRef=useRef<HTMLButtonElement>(null);const total=useMemo(()=>items.reduce((s,x)=>s+x.amount,0),[items]);
useEffect(()=>{const add=(e:Event)=>{const d=(e as CustomEvent<AddBasketDetail>).detail;if(!d||!d.project||!Number.isFinite(d.amount)||d.amount<=0)return;setItems(c=>[...c,{...d,id:Date.now()+Math.random()}])};window.addEventListener("minber:add-to-basket",add);return()=>window.removeEventListener("minber:add-to-basket",add)},[]);
useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);triggerRef.current?.focus()}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key)}},[open]);const change=(id:number,n:1|-1)=>setItems(c=>c.map(x=>x.id===id?{...x,amount:Math.max(1,x.amount+n*25)}:x));
return <><button ref={triggerRef} type="button" className={`basket-trigger ${compact?"basket-trigger--compact":""}`} aria-label={`سلة العطاء، ${items.length} عناصر`} aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><BasketIcon/>{!compact&&<span>سلة العطاء</span>}<span className="basket-count" aria-hidden="true">{items.length}</span></button>{open&&<div className="drawer-layer"><button className="drawer-backdrop" type="button" aria-label="إغلاق سلة العطاء" onClick={()=>setOpen(false)}/><aside className="basket-drawer" role="dialog" aria-modal="true" aria-labelledby="basket-title"><div className="drawer-header"><div><span className="drawer-kicker">واجهة تجريبية</span><h2 id="basket-title">سلة العطاء</h2></div><IconButton ref={closeRef} aria-label="إغلاق السلة" onClick={()=>setOpen(false)}><CloseIcon/></IconButton></div>{items.length===0?<div className="basket-empty"><BasketIcon width={34} height={34}/><h3>سلة العطاء فارغة</h3><p>أضف مشروعًا أو خطة لتظهر هنا.</p><Button href="/projects" variant="outline">استكشف المشاريع</Button></div>:<div className="basket-items" aria-live="polite">{items.map(x=><article className={`basket-item basket-item--${x.intent}`} key={x.id}><div className="basket-item-top"><Badge tone={x.intent==="zakat"?"zakat":x.intent==="waqf"?"waqf":x.intent==="urgent"?"urgent":"neutral"}>{x.intentLabel}</Badge><IconButton aria-label={`إزالة ${x.project}`} onClick={()=>setItems(c=>c.filter(y=>y.id!==x.id))}><TrashIcon width={17} height={17}/></IconButton></div><h3>{x.project}</h3><div className="basket-item-context"><span>{x.donationMode?modeLabels[x.donationMode]:"مرة واحدة"}</span>{x.frequency&&<span>الدورية: {x.frequency}</span>}{x.intent==="recurring"&&<span>المبلغ لكل عملية: {x.amount} USD</span>}{x.estimatedMonthly!==undefined&&<span>تقدير شهري: {x.estimatedMonthly} USD</span>}{x.estimatedAnnual!==undefined&&<span>تقدير سنوي: {x.estimatedAnnual} USD</span>}{x.startPreference&&<span>بداية الخطة: {x.startPreference==="next-month"?"بداية الشهر القادم":"بعد التأكيد"}</span>}{x.receiptType==="zakat"&&<span>إيصال زكاة مستقل</span>}{x.receiptType==="recurring"&&<span>إيصال مع كل عملية</span>}{x.certificateType==="waqf"&&<span>شهادة وقف</span>}</div><div className="basket-item-bottom"><strong>{x.amount} {x.currency}</strong><div className="amount-controls" aria-label={`تعديل مبلغ ${x.project}`}><IconButton aria-label="خفض المبلغ" onClick={()=>change(x.id,-1)}><MinusIcon width={16} height={16}/></IconButton><span>تعديل بصري</span><IconButton aria-label="زيادة المبلغ" onClick={()=>change(x.id,1)}><PlusIcon width={16} height={16}/></IconButton></div></div></article>)}</div>}<div className="basket-summary"><div><span>الإجمالي</span><strong>{total} USD</strong></div><Button disabled={items.length===0} fullWidth>مراجعة سلة العطاء</Button><small>Frontend Prototype — لا يتم حفظ الخطط أو تنفيذ الدفع.</small></div></aside></div>}</>}
