"use client";
import { useEffect,useMemo,useRef,useState } from "react";
import { Badge } from "./badge";import { Button } from "./button";import { BasketIcon,CloseIcon,MinusIcon,PlusIcon,TrashIcon } from "./icons";import { IconButton } from "./icon-button";
type Item={id:number;intent:"zakat"|"waqf"|"urgent";intentLabel:string;project:string;amount:number;currency:"USD"};
const initial:Item[]=[{id:1,intent:"zakat",intentLabel:"زكاة",project:"زكاة لفلسطين",amount:120,currency:"USD"},{id:2,intent:"waqf",intentLabel:"وقف",project:"سهم وقفي للقدس",amount:250,currency:"USD"},{id:3,intent:"urgent",intentLabel:"إغاثة عاجلة",project:"إغاثة غزة",amount:75,currency:"USD"}];
export function BasketTrigger({compact=false}:{compact?:boolean}){const [open,setOpen]=useState(false),[items,setItems]=useState(initial);const closeRef=useRef<HTMLButtonElement>(null),triggerRef=useRef<HTMLButtonElement>(null);const total=useMemo(()=>items.reduce((s,x)=>s+x.amount,0),[items]);
 useEffect(()=>{if(!open)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";closeRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);triggerRef.current?.focus()}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key)}},[open]);
 const change=(id:number,d:1|-1)=>setItems(v=>v.map(x=>x.id===id?{...x,amount:Math.max(25,x.amount+d*25)}:x));
 return <><button ref={triggerRef} type="button" className={`basket-trigger ${compact?"basket-trigger--compact":""}`} aria-label={`سلة العطاء، ${items.length} عناصر`} aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><BasketIcon/>{!compact?<span>سلة العطاء</span>:null}<span className="basket-count" aria-hidden="true">{items.length}</span></button>{open?<div className="drawer-layer"><button className="drawer-backdrop" type="button" aria-label="إغلاق سلة العطاء" onClick={()=>setOpen(false)}/><aside className="basket-drawer" role="dialog" aria-modal="true" aria-labelledby="basket-title"><div className="drawer-header"><div><span className="drawer-kicker">واجهة تجريبية</span><h2 id="basket-title">سلة العطاء</h2></div><IconButton ref={closeRef} aria-label="إغلاق السلة" onClick={()=>setOpen(false)}><CloseIcon/></IconButton></div>{items.length===0?<div className="basket-empty"><BasketIcon width={34} height={34}/><h3>سلة العطاء فارغة</h3><p>أضف مشروعًا أو نية تبرع لتظهر هنا قبل المراجعة.</p><Button href="#projects" variant="outline" onClick={()=>setOpen(false)}>استكشف المشاريع</Button></div>:<div className="basket-items" aria-live="polite">{items.map(item=><article className={`basket-item basket-item--${item.intent}`} key={item.id}><div className="basket-item-top"><Badge tone={item.intent}>{item.intentLabel}</Badge><IconButton aria-label={`إزالة ${item.project}`} onClick={()=>setItems(v=>v.filter(x=>x.id!==item.id))}><TrashIcon width={17} height={17}/></IconButton></div><h3>{item.project}</h3><div className="basket-item-bottom"><strong>{item.amount} {item.currency}</strong><div className="amount-controls" aria-label={`تعديل مبلغ ${item.project}`}><IconButton aria-label="خفض المبلغ" onClick={()=>change(item.id,-1)}><MinusIcon width={16} height={16}/></IconButton><span>تعديل</span><IconButton aria-label="زيادة المبلغ" onClick={()=>change(item.id,1)}><PlusIcon width={16} height={16}/></IconButton></div></div></article>)}</div>}<div className="basket-summary"><div><span>الإجمالي</span><strong>{total} USD</strong></div><Button disabled={items.length===0} fullWidth>مراجعة سلة العطاء</Button><button type="button" className="text-action" onClick={()=>setItems([])}>عرض الحالة الفارغة</button><small>نموذج Frontend فقط — لا يتم حفظ البيانات أو تنفيذ الدفع.</small></div></aside></div>:null}</>}
