import {ProjectFaq} from "@/components/project-detail/project-faq";
import {Button} from "@/components/ui/button";
import {Container} from "@/components/ui/container";
import type {ProjectMetric} from "@/data/project-metrics";
import type {ProjectRecord,ProjectRegion,ProjectStatus} from "@/data/projects";
import {zakatDistributionSteps,zakatFaqs,zakatProofItems,zakatSeparationItems,zakatShariaReviewFields,zakatTrustItems} from "@/data/zakat";
import {ZakatCalculator} from "./zakat-calculator";
const R:Record<ProjectRegion,string>={"al-quds":"القدس","al-aqsa":"الأقصى",gaza:"غزة",syria:"سوريا",sudan:"السودان",yemen:"اليمن",global:"عام"};
const S:Record<ProjectStatus,string>={active:"نشط",seasonal:"موسمي",archived:"مكتمل","needs-verification":"قيد التحقق"};
function Media({p}:{p:ProjectRecord}){return p.image?<figure className="z-project-media"><img src={p.image.sourceUrl} alt={p.image.alt.ar}/><figcaption>Temporary official source · final approval required</figcaption></figure>:<div className="z-placeholder"><strong>APPROVED ZAKAT PROJECT IMAGE REQUIRED</strong><span>Verified field source · Dignified beneficiaries · No AI</span></div>}
function Metric({m,title}:{m?:ProjectMetric;title:string}){if(!m)return <p className="z-data">بيانات التمويل قيد التحقق</p>;const v=Math.min(100,m.raised/m.goal*100);return <div className="z-metric"><div role="progressbar" aria-label={`نسبة تمويل ${title}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(v)}><span style={{width:`${v}%`}}/></div><p><strong>{m.raised.toLocaleString("en-US")} USD</strong><span>من {m.goal.toLocaleString("en-US")} USD</span></p><small>DATA REQUIRES FINAL VERIFICATION</small></div>}
export function ZakatPageSections({projects,metrics}:{projects:ProjectRecord[];metrics:ProjectMetric[]}){const choices=projects.map(p=>({id:p.id,slug:p.slug,title:p.title.ar}));return <>
<div className="z-breadcrumb"><Container><nav aria-label="مسار التنقل"><a href="/">الرئيسية</a><span>←</span><span aria-current="page">الزكاة</span></nav></Container></div>
<section className="z-hero" aria-labelledby="z-hero-title"><Container className="z-hero-grid"><div><span className="z-kicker">مسار مستقل وواضح للزكاة</span><h1 id="z-hero-title">أخرج زكاتك لفلسطين بثقة</h1><p>احسب مقدار زكاتك تقديريًا، وثبّت نيتك، واختر مسارًا مؤهلًا لدعم المحتاجين في فلسطين ضمن تجربة واضحة ومنفصلة.</p><div className="z-actions"><Button href="#zakat-calculator" size="large">احسب زكاتك</Button><Button href="#zakat-projects" variant="outline" size="large">استكشف مشاريع الزكاة</Button></div><ul><li>نية منفصلة</li><li>إيصال زكاة مستقل</li><li>مشاريع مؤهلة فقط</li><li>تحديثات توزيع</li></ul><div className="z-warning"><strong>الحاسبة تقديرية ولا تُعد فتوى شرعية</strong><span>Prototype calculation only</span></div></div><div className="z-hero-visual"><div className="z-placeholder"><strong>APPROVED ZAKAT FIELD IMAGE REQUIRED</strong><span>Real Palestine distribution context · Verified source · Dignified beneficiaries · No AI · No money imagery</span><small>Minimum 2200 × 1400 · Independent mobile crop</small></div><ol><li>احسب</li><li>ثبّت النية</li><li>اختر المشروع</li><li>تابع الأثر</li></ol></div></Container></section>
<section className="z-trust" aria-label="مبادئ تجربة الزكاة"><Container>{zakatTrustItems.map(([t,d],i)=><div key={t}><span>0{i+1}</span><strong>{t}</strong><p>{d}</p></div>)}</Container></section>
<Container><ZakatCalculator projects={choices}/></Container>
<section className="z-separation"><Container><header><span>فصل الأموال والنية</span><h2>زكاتك تبقى في مسار مستقل</h2><p>تُعامل الزكاة كنية وإيصال ومسار توزيع مستقلين، ولا تختلط بالصدقة أو الوقف.</p></header><ol>{zakatSeparationItems.map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></Container></section>
<section className="z-distribution"><Container><header><span>مسار عام يحتاج الاعتماد</span><h2>كيف تُوجّه زكاتك؟</h2><p>تفاصيل سياسة التوزيع تحتاج اعتماد المؤسسة والمراجعة الشرعية.</p></header><ol>{zakatDistributionSteps.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></li>)}</ol></Container></section>
<section className="z-projects" id="zakat-projects"><Container><header><span>من data/projects.ts</span><h2>مشاريع تقبل الزكاة</h2><p>لا يظهر أي مشروع لا يحتوي على نوع العطاء zakat.</p></header><div className="z-project-grid">{projects.slice(0,3).map(p=>{const m=metrics.find(x=>x.projectId===p.id);return <article key={p.id}><Media p={p}/><div><small>{R[p.region]} · {S[p.status]}</small><h3>{p.title.ar}</h3><p>{p.summary.ar}</p><div className="z-proof-line">✓ {p.image?"مصدر ميداني مؤقت يحتاج الاعتماد":"وسائط وتوثيق مطلوبان"}</div><Metric m={m} title={p.title.ar}/><footer><Button href={`/projects/${p.slug}`} variant="outline">عرض المشروع</Button><Button href="#zakat-calculator" variant="ghost">أضف زكاتك</Button></footer></div></article>})}</div></Container></section>
<section className="z-proof"><Container><header><span>الشفافية</span><h2>توثيق توزيع الزكاة</h2><p>لا تُعرض وثيقة غير موجودة، وتبقى حالة كل عنصر ظاهرة.</p></header><div className="z-proof-grid"><div>{zakatProofItems.map(([t,s,n])=><article key={t}><span>✓</span><div><h3>{t}</h3><strong>{s}</strong><p>{n}</p></div></article>)}</div><aside><small>معاينة تصميمية فقط</small><div>OFFICIAL LOGO REQUIRED</div><h3>مؤسسة منبر الأقصى الدولية</h3><p>نوع الإيصال</p><strong>إيصال زكاة</strong><dl><div><dt>المبلغ</dt><dd>سيظهر بعد الحساب</dd></div><div><dt>العملة</dt><dd>USD</dd></div><div><dt>المسار</dt><dd>مشروع أو صندوق الزكاة</dd></div></dl><code>PREVIEW-ZAKAT-0001</code></aside></div></Container></section>
<section className="z-sharia"><Container><div><span>SHARIA REVIEW REQUIRED</span><h2>المراجعة الشرعية</h2><p>لا تعرض هذه الوحدة فتوى أو اسم جهة غير مؤكدة.</p></div><dl>{zakatShariaReviewFields.map(f=><div key={f}><dt>{f}</dt><dd>بيانات مطلوبة</dd></div>)}</dl></Container></section>
<section className="z-faq"><Container><header><span>قبل إتمام الزكاة</span><h2>أسئلة شائعة عن التجربة</h2></header><ProjectFaq items={[...zakatFaqs]}/></Container></section>
<section className="z-final"><Container><div><span>نية واضحة · مسار مستقل</span><h2>احسب زكاتك ثم اختر المشروع المؤهل</h2><p>لن تُرسل بيانات الحاسبة أو تُحفظ، ولن يتم تنفيذ دفع حقيقي.</p></div><Button href="#zakat-calculator" size="large">ابدأ الحساب التقديري</Button></Container></section>
</>}
