"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Button} from "@/components/ui/button";

type Project={id:string;slug:string;title:string};
type Allocation={id:number;target:string;amount:string};
const FIELDS=["النقد والمدخرات","الذهب والفضة","الاستثمارات والتجارة","المستحقات المتوقع تحصيلها","أصول زكوية أخرى"];
const clean=(v:string)=>v.replace(/[^0-9.]/g,"").replace(/(\..*)\./g,"$1");
const num=(v:string)=>Number(v)||0;
const focusable='button:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])';

export function ZakatCalculator({projects}:{projects:Project[]}){
 const [assets,setAssets]=useState<string[]>(FIELDS.map(()=>"")),[liabilities,setLiabilities]=useState(""),[nisab,setNisab]=useState("");
 const [custom,setCustom]=useState(""),[useEstimate,setUseEstimate]=useState(true),[intent,setIntent]=useState(false);
 const [alloc,setAlloc]=useState<Allocation[]>([{id:1,target:"zakat-fund",amount:""}]),[message,setMessage]=useState(""),[toast,setToast]=useState(false),[sheet,setSheet]=useState(false),[step,setStep]=useState(1);
 const sheetRef=useRef<HTMLElement|null>(null),triggerRef=useRef<HTMLButtonElement|null>(null);
 const result=useMemo(()=>{const total=assets.reduce((s,v)=>s+num(v),0),net=Math.max(0,total-num(liabilities));return{total,net,zakat:net*.025}},[assets,liabilities]);
 const selected=useEstimate?result.zakat:num(custom),allocated=alloc.reduce((s,a)=>s+num(a.amount),0),remaining=Math.max(0,selected-allocated),exceeded=allocated>selected+.001;
 const targets=[{id:"zakat-fund",title:"صندوق زكاة فلسطين"},...projects.map(p=>({id:p.id,title:p.title}))];
 const valid=selected>0&&intent&&allocated>0&&!exceeded&&alloc.every(a=>num(a.amount)>0);
 useEffect(()=>{if(useEstimate&&alloc.length===1&&alloc[0].target==="zakat-fund")setAlloc([{...alloc[0],amount:result.zakat?result.zakat.toFixed(2):""}])},[result.zakat,useEstimate]);
 useEffect(()=>{if(!sheet||!sheetRef.current)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const el=sheetRef.current;const items=()=>Array.from(el.querySelectorAll<HTMLElement>(focusable));setTimeout(()=>items()[0]?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSheet(false);if(e.key!=="Tab")return;const a=items(),first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key);triggerRef.current?.focus()}},[sheet]);
 const setAsset=(i:number,v:string)=>setAssets(x=>x.map((a,n)=>n===i?clean(v):a));
 const update=(id:number,patch:Partial<Allocation>)=>setAlloc(x=>x.map(a=>a.id===id?{...a,...patch}:a));
 const addRow=()=>alloc.length<3&&setAlloc(x=>[...x,{id:Date.now(),target:projects.find(p=>!x.some(a=>a.target===p.id))?.id||"zakat-fund",amount:""}]);
 const fullFund=()=>setAlloc([{id:Date.now(),target:"zakat-fund",amount:selected?selected.toFixed(2):""}]);
 const reset=()=>{setAssets(FIELDS.map(()=>""));setLiabilities("");setNisab("");setCustom("");setUseEstimate(true);setIntent(false);setAlloc([{id:Date.now(),target:"zakat-fund",amount:""}]);setMessage("")};
 const addBasket=()=>{if(!valid){setMessage("أكمل المبلغ وتأكيد النية والتوزيع دون تجاوز الإجمالي.");return}alloc.forEach(a=>{const p=projects.find(x=>x.id===a.target);window.dispatchEvent(new CustomEvent("minber:add-to-basket",{detail:{intent:"zakat",intentLabel:"زكاة",projectId:p?.id,fundId:p?undefined:"zakat-fund",slug:p?.slug,project:p?.title||"صندوق زكاة فلسطين",donationMode:"one-time",amount:num(a.amount),currency:"USD",source:"zakat-page",calculationReference:"prototype",receiptType:"zakat"}}))});setMessage("تمت إضافة مسارات الزكاة إلى سلة العطاء بصورة مستقلة.");setToast(true);setTimeout(()=>setToast(false),2200)};
 const checkout=()=>setMessage(valid?"سيتم الانتقال إلى Checkout بعد ربط نظام الدفع. لا يتم تنفيذ دفع حقيقي الآن.":"أكمل النية والتوزيع قبل المتابعة.");
 const summary=<div className="z-summary" aria-live="polite"><span>ملخص تقديري</span><div><small>صافي المال الزكوي</small><strong>{result.net.toFixed(2)} USD</strong></div><div><small>مقدار الزكاة المحدد</small><strong>{selected.toFixed(2)} USD</strong></div><div><small>تم توزيعه</small><strong>{allocated.toFixed(2)} USD</strong></div><div><small>المتبقي</small><strong>{remaining.toFixed(2)} USD</strong></div><p>نتيجة تقديرية وليست حكمًا شرعيًا.</p></div>;
 return <>
 <section id="zakat-calculator" className="z-tool" aria-labelledby="z-tool-title"><header><span>Prototype calculation only</span><h2 id="z-tool-title">احسب مقدار زكاتك تقديريًا</h2><p>تحقق من النصاب وحولان الحول والأحكام الخاصة بحالتك مع جهة شرعية معتمدة.</p></header>
 <nav className="z-steps" aria-label="مراحل الحاسبة">{["الأصول","الالتزامات","النتيجة والنية","اختيار المسار"].map((x,i)=><button key={x} aria-pressed={step===i+1} onClick={()=>setStep(i+1)}><b>{i+1}</b>{x}</button>)}</nav>
 <div className="z-grid"><div className="z-form">
 <fieldset className={step===1?"active":""}><legend>1. الأصول الزكوية</legend><div className="z-inputs">{FIELDS.map((f,i)=><label key={f}><span>{f}</span><div><input inputMode="decimal" value={assets[i]} onChange={e=>setAsset(i,e.target.value)} placeholder="0.00"/><b>USD</b></div></label>)}</div><Button type="button" variant="outline" onClick={()=>setStep(2)}>التالي</Button></fieldset>
 <fieldset className={step===2?"active":""}><legend>2. الالتزامات والنصاب</legend><label><span>الالتزامات قصيرة الأجل</span><div><input inputMode="decimal" value={liabilities} onChange={e=>setLiabilities(clean(e.target.value))}/><b>USD</b></div></label><div className="z-nisab"><strong>قيمة النصاب الحالية</strong><p>تحتاج ربطًا بمصدر شرعي ومالي معتمد</p><label><span>أدخل قيمة النصاب التي تعتمدها — اختياري</span><div><input inputMode="decimal" value={nisab} onChange={e=>setNisab(clean(e.target.value))}/><b>USD</b></div></label>{num(nisab)>0&&<small>{result.net>=num(nisab)?"أعلى من القيمة المدخلة":"أقل من القيمة المدخلة"} — تحقق من بقية الشروط الشرعية.</small>}</div><Button type="button" variant="outline" onClick={()=>setStep(3)}>التالي</Button></fieldset>
 <section className={step===3?"z-result active":"z-result"}><span>3. النتيجة التقديرية</span><h3>نتيجة الحاسبة</h3><dl><div><dt>إجمالي الأصول</dt><dd>{result.total.toFixed(2)} USD</dd></div><div><dt>صافي المال الزكوي</dt><dd>{result.net.toFixed(2)} USD</dd></div><div><dt>2.5% تقديريًا</dt><dd>{result.zakat.toFixed(2)} USD</dd></div></dl><label><input type="radio" checked={useEstimate} onChange={()=>setUseEstimate(true)}/>استخدام المبلغ المحسوب كاملًا</label><label><input type="radio" checked={!useEstimate} onChange={()=>setUseEstimate(false)}/>إدخال مبلغ مختلف</label>{!useEstimate&&<label><span>مبلغ الزكاة</span><div><input inputMode="decimal" value={custom} onChange={e=>setCustom(clean(e.target.value))}/><b>USD</b></div></label>}<label className="z-intent"><input type="checkbox" checked={intent} onChange={e=>setIntent(e.target.checked)}/><span><strong>أنوي هذا المبلغ زكاة</strong><small>ستبقى هذه النية منفصلة داخل سلة العطاء والإيصال.</small></span></label>{!intent&&<small className="field-error">تأكيد النية مطلوب.</small>}<Button type="button" variant="outline" onClick={()=>setStep(4)}>التالي</Button></section>
 <section className={step===4?"z-allocation active":"z-allocation"}><header><div><span>4. توزيع الزكاة</span><h3>اختر الصندوق أو المشاريع المؤهلة</h3></div><button onClick={fullFund}>توجيه كامل المبلغ للصندوق</button></header>{alloc.map((a,i)=><div className="z-row" key={a.id}><b>{i+1}</b><select value={a.target} onChange={e=>update(a.id,{target:e.target.value})}>{targets.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><div><input inputMode="decimal" value={a.amount} onChange={e=>update(a.id,{amount:clean(e.target.value)})}/><b>USD</b></div>{alloc.length>1&&<button aria-label="إزالة المسار" onClick={()=>setAlloc(x=>x.filter(r=>r.id!==a.id))}>×</button>}</div>)}<footer><Button type="button" variant="outline" onClick={addRow} disabled={alloc.length>=3}>قسّم على مشروع آخر</Button><span>المتبقي: <strong>{remaining.toFixed(2)} USD</strong></span></footer>{exceeded&&<p className="field-error">مجموع التوزيع يتجاوز مبلغ الزكاة.</p>}</section>
 <div className="z-privacy"><strong>خصوصية الحاسبة</strong><p>تظل البيانات داخل المتصفح ولا يتم إرسالها أو حفظها.</p><button onClick={reset}>مسح الحاسبة</button></div></div>
 <aside className="z-side">{summary}<Button fullWidth onClick={checkout}>أخرج زكاتك الآن</Button><Button fullWidth variant="outline" onClick={addBasket}>أضف الزكاة إلى سلة العطاء</Button>{message&&<p role="status">{message}</p>}<small>لا تُرسل تفاصيل الأصول أو المدخرات إلى السلة.</small></aside></div></section>
 <div className="z-mobile-bar"><div><small>مقدار الزكاة التقديري</small><strong>{selected.toFixed(2)} USD</strong></div><button ref={triggerRef} onClick={()=>setSheet(true)}>أكمل زكاتك</button></div>
 {sheet&&<div className="z-layer"><button className="z-backdrop" aria-label="إغلاق" onClick={()=>setSheet(false)}/><aside ref={sheetRef} className="z-sheet" role="dialog" aria-modal="true" aria-labelledby="z-sheet-title"><header><h2 id="z-sheet-title">أكمل زكاتك</h2><button onClick={()=>setSheet(false)} aria-label="إغلاق">×</button></header>{summary}<Button fullWidth onClick={addBasket}>أضف إلى السلة</Button><Button fullWidth variant="outline" onClick={checkout}>أخرج زكاتك الآن</Button>{message&&<p role="status">{message}</p>}</aside></div>}
 <div className={toast?"toast is-visible":"toast"} role="status" aria-live="polite">تمت إضافة الزكاة إلى السلة</div></>;
}
