import { ProjectFaq } from "@/components/project-detail/project-faq";
import { AlQudsGoldCoin } from "@/components/brand/al-quds-gold-coin";
import { GoldenIdentityPattern } from "@/components/brand/golden-identity-pattern";
import { GoldenSectionDivider } from "@/components/brand/golden-section-divider";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import type { ProjectMetric } from "@/data/project-metrics";
import type { ProjectRecord, ProjectRegion, ProjectStatus } from "@/data/projects";
import { zakatDistributionSteps, zakatFaqs, zakatProofItems, zakatSeparationItems, zakatShariaReviewFields, zakatTrustItems } from "@/data/zakat";
import { ZakatCalculator } from "./zakat-calculator";

const R: Record<ProjectRegion, string> = { "al-quds": "القدس", "al-aqsa": "الأقصى", gaza: "غزة", syria: "سوريا", sudan: "السودان", yemen: "اليمن", global: "عام" };
const S: Record<ProjectStatus, string> = { active: "نشط", seasonal: "موسمي", archived: "مكتمل", "needs-verification": "قيد التحقق" };
const quickAmounts = [25, 50, 100, 250, 500];

function Media({ p }: { p: ProjectRecord }) { return p.image ? <figure className="z-project-media"><img src={p.image.sourceUrl} alt={p.image.alt.ar} /><figcaption>Temporary official source · final approval required</figcaption></figure> : <div className="z-placeholder"><strong>APPROVED ZAKAT PROJECT IMAGE REQUIRED</strong><span>Verified field source · Dignified beneficiaries · No AI</span></div>; }
function Metric({ m, title }: { m?: ProjectMetric; title: string }) { if (!m) return <p className="z-data">بيانات التمويل قيد التحقق</p>; const value = Math.min(100, m.raised / m.goal * 100); return <div className="z-metric"><div role="progressbar" aria-label={`نسبة تمويل ${title}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(value)}><span style={{ width: `${value}%` }} /></div><p><strong>{m.raised.toLocaleString("en-US")} USD</strong><span>من {m.goal.toLocaleString("en-US")} USD</span></p><small>DATA REQUIRES FINAL VERIFICATION</small></div>; }

export function ZakatPageSections({ projects, metrics }: { projects: ProjectRecord[]; metrics: ProjectMetric[] }) {
  const choices = projects.map((project) => ({ id: project.id, slug: project.slug, title: project.title.ar }));
  return <>
    <div className="z-breadcrumb"><Container><nav aria-label="مسار التنقل"><a href="/">الرئيسية</a><span>←</span><span aria-current="page">الزكاة</span></nav></Container></div>
    <section className="z-hero z-hero--golden" aria-labelledby="z-hero-title"><GoldenIdentityPattern /><Container className="z-hero-grid"><div className="z-hero-copy"><span className="z-kicker">زكاة واضحة الأثر لفلسطين</span><h1 id="z-hero-title">أخرج زكاتك لفلسطين</h1><p>احسب مقدار زكاتك تقديريًا، وثبّت نيتك، ثم وجّهها إلى صندوق الزكاة أو مشروع مؤهل ضمن مسار مستقل وواضح.</p><div className="z-quick-amounts" aria-label="مبالغ سريعة للانتقال إلى الحاسبة">{quickAmounts.map((amount) => <a key={amount} href="#zakat-calculator"><strong>{amount}</strong><span>USD</span></a>)}</div><div className="z-actions"><Button href="#zakat-calculator" size="large">أخرج زكاتك الآن</Button><Button href="#zakat-calculator" variant="outline" size="large">احسب زكاتك</Button><Button href="/recurring?intent=zakat" variant="ghost" size="large">زكاة شهرية — Prototype</Button></div><ul><li>نية منفصلة</li><li>إيصال زكاة مستقل</li><li>مشاريع مؤهلة فقط</li><li>خصوصية الحاسبة</li></ul><div className="z-warning"><strong>الحاسبة تقديرية ولا تُعد فتوى شرعية</strong><span>Prototype calculation only</span></div></div><div className="z-hero-visual z-hero-visual--coin"><AlQudsGoldCoin priority /><ol><li>احسب</li><li>ثبّت النية</li><li>اختر المشروع</li><li>تابع الأثر</li></ol></div></Container></section>
    <Container><ZakatCalculator projects={choices} /></Container>
    <section className="z-separation"><Container><header><span>فصل الأموال والنية</span><h2>زكاتك تبقى في مسار مستقل</h2><p>تُعامل الزكاة كنية وإيصال ومسار توزيع مستقلين، ولا تختلط بالصدقة أو الوقف.</p></header><ol>{zakatSeparationItems.map(([n, title, description]) => <li key={n}><span>{n}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></Container></section>
    <section className="z-distribution z-editorial"><Container><div className="z-editorial-copy"><GoldenSectionDivider label="مسار التوزيع" /><h2>كيف تُوجّه زكاتك؟</h2><p>تفاصيل سياسة التوزيع تحتاج اعتماد المؤسسة والمراجعة الشرعية، لذلك تبقى الحالة واضحة دون ادعاءات غير موثقة.</p></div><ol>{zakatDistributionSteps.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item}</strong></li>)}</ol></Container></section>
    <section className="z-projects" id="zakat-projects"><Container><header><span>مشاريع مؤهلة فقط</span><h2>مشاريع تقبل الزكاة</h2><p>لا يظهر أي مشروع لا يحتوي على نوع العطاء zakat.</p></header><div className="z-project-grid">{projects.slice(0, 3).map((project) => { const metric = metrics.find((item) => item.projectId === project.id); return <article key={project.id}><Media p={project} /><div><small>{R[project.region]} · {S[project.status]}</small><h3>{project.title.ar}</h3><p>{project.summary.ar}</p><div className="z-proof-line">✓ {project.image ? "مصدر ميداني مؤقت يحتاج الاعتماد" : "وسائط وتوثيق مطلوبان"}</div><Metric m={metric} title={project.title.ar} /><footer><Button href={`/projects/${project.slug}`} variant="outline">عرض المشروع</Button><Button href="#zakat-calculator" variant="ghost">أضف زكاتك</Button></footer></div></article>; })}</div></Container></section>
    <section className="z-proof"><Container><header><span>الشفافية</span><h2>توثيق توزيع الزكاة</h2><p>لا تُعرض وثيقة غير موجودة، وتبقى حالة كل عنصر ظاهرة.</p></header><div className="z-proof-grid"><div>{zakatProofItems.map(([title, status, note]) => <article key={title}><span>✓</span><div><h3>{title}</h3><strong>{status}</strong><p>{note}</p></div></article>)}</div><aside><small>معاينة تصميمية فقط</small><div>OFFICIAL LOGO REQUIRED</div><h3>مؤسسة منبر الأقصى الدولية</h3><p>نوع الإيصال</p><strong>إيصال زكاة</strong><dl><div><dt>المبلغ</dt><dd>سيظهر بعد الحساب</dd></div><div><dt>العملة</dt><dd>USD</dd></div><div><dt>المسار</dt><dd>مشروع أو صندوق الزكاة</dd></div></dl><code>PREVIEW-ZAKAT-0001</code></aside></div></Container></section>
    <section className="z-sharia"><Container><div><span>SHARIA REVIEW REQUIRED</span><h2>المراجعة الشرعية</h2><p>لا تعرض هذه الوحدة فتوى أو نصًا شرعيًا غير معتمد.</p></div><dl>{zakatShariaReviewFields.map((field) => <div key={field}><dt>{field}</dt><dd>بيانات مطلوبة</dd></div>)}</dl></Container></section>
    <section className="z-faq"><Container><header><span>قبل إتمام الزكاة</span><h2>أسئلة شائعة عن التجربة</h2></header><ProjectFaq items={[...zakatFaqs]} /></Container></section>
    <section className="z-trust z-trust--final" aria-label="مبادئ تجربة الزكاة"><Container>{zakatTrustItems.map(([title, description], index) => <div key={title}><span>0{index + 1}</span><strong>{title}</strong><p>{description}</p></div>)}</Container></section>
    <section className="z-final"><Container><div><span>نية واضحة · مسار مستقل</span><h2>احسب زكاتك ثم اختر المشروع المؤهل</h2><p>لن تُرسل بيانات الحاسبة أو تُحفظ، ولن يتم تنفيذ دفع حقيقي.</p></div><Button href="#zakat-calculator" size="large">ابدأ الحساب التقديري</Button></Container></section>
  </>;
}
