import type { ProductionItem, ProductionStage } from "./production-types";

export const productionStages: { stage: ProductionStage; title: string; description: string }[] = [
  { stage: "IDEA", title: "الأفكار", description: "مواد مقترحة ولم تتحول بعد إلى نصوص." },
  { stage: "SCRIPT", title: "النصوص", description: "نصوص قيد الكتابة أو المراجعة." },
  { stage: "DESIGN", title: "التصميم", description: "بوسترات وكاروسيل قيد التصميم." },
  { stage: "VIDEO", title: "الفيديو", description: "مونتاج أو تصوير أو تجهيز فيديو." },
  { stage: "REVIEW", title: "المراجعة", description: "مراجعة شرعية أو لغوية أو إدارية." },
  { stage: "READY", title: "جاهز للتسويق", description: "مواد جاهزة للتسليم أو الاستخدام." },
  { stage: "PUBLISHED", title: "منشور", description: "مواد منشورة أو مستخدمة في الحملات." },
];

export const productionItems: ProductionItem[] = [
  {
    id: "prod-ramadan-video-01",
    taskId: "task-ramadan-videos",
    title: "فيديو افتتاح حملة رمضان",
    stage: "VIDEO",
    priority: "HIGH",
    seasonTitle: "رمضان",
    contentType: "Video",
    owner: "فريق الميديا",
    dueLabel: "هذا الأسبوع",
    scriptUrl: "قيد الإعداد",
    videoUrl: "قيد المونتاج",
    isDeliveredToMarketing: false,
    isUsedInAds: false,
  },
  {
    id: "prod-ramadan-design-01",
    taskId: "task-ramadan-designs",
    title: "تصميم نداء السلة الغذائية",
    stage: "DESIGN",
    priority: "HIGH",
    seasonTitle: "رمضان",
    contentType: "Poster",
    owner: "فريق التصميم",
    dueLabel: "هذا الأسبوع",
    designUrl: "قيد التصميم",
    isDeliveredToMarketing: false,
    isUsedInAds: false,
  },
  {
    id: "prod-waqf-carousel-01",
    title: "كاروسيل أثر الوقف في القدس",
    stage: "SCRIPT",
    priority: "MEDIUM",
    seasonTitle: "الوقف للقدس",
    contentType: "Carousel",
    owner: "فريق المحتوى",
    dueLabel: "الأسبوع القادم",
    scriptUrl: "مسودة أولى",
    isDeliveredToMarketing: false,
    isUsedInAds: false,
  },
  {
    id: "prod-friday-message-01",
    title: "رسالة واتساب لعطاء الجمعة",
    stage: "READY",
    priority: "MEDIUM",
    seasonTitle: "الجمعة",
    contentType: "WhatsApp",
    owner: "فريق التسويق",
    dueLabel: "جاهز",
    scriptUrl: "نص معتمد",
    isDeliveredToMarketing: true,
    isUsedInAds: false,
  },
  {
    id: "prod-gaza-reel-01",
    title: "ريل توزيع عاجل لغزة",
    stage: "PUBLISHED",
    priority: "HIGH",
    seasonTitle: "غزة العاجلة",
    contentType: "Reel",
    owner: "فريق الميديا",
    dueLabel: "منشور",
    videoUrl: "تم النشر",
    isDeliveredToMarketing: true,
    isUsedInAds: true,
    resultLabel: "مستخدم في إعلان Meta",
  },
];
