export type DashboardDbContractContext = "operations" | "archive" | "brand" | "ai";
export type DashboardDbContractStatus = "FOUNDATION" | "PRISMA_READY" | "DB_BACKED";
export type DashboardDbMigrationRisk = "LOW" | "MEDIUM" | "HIGH";

export type DashboardDbContract = {
  name: string;
  context: DashboardDbContractContext;
  status: DashboardDbContractStatus;
  purpose: string;
  currentPersistence: string;
  nextModel: string;
  readyForPrisma: boolean;
  migrationRisk: DashboardDbMigrationRisk;
  fields: string[];
  indexes: string[];
  safety: string[];
  repositoryOwner: string;
};

const operationsSafety = [
  "No automatic sending",
  "No automatic publishing",
  "No payment changes",
  "No tracking runtime changes",
  "Human approval remains required for outbound actions",
];

const archiveSafety = [
  "Google Drive metadata only",
  "No automatic AI analysis",
  "No automatic approval",
  "Sensitive assets require human review",
  "No separate archive task system",
];

const brandSafety = [
  "Brand assets stay separate from ArchiveAsset",
  "No frontend secrets",
  "Downloads expose only approved public asset URLs",
  "AI output remains draft-only",
];

const aiSafety = [
  "No external AI call without safe provider configuration",
  "No sending, publishing, budget, or tracking changes",
  "Audit records must not store secrets",
  "All write actions are write-proposed until approved",
];

export const dashboardDbContracts: DashboardDbContract[] = [
  {
    name: "OperationSeason",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Stores reviewed operational seasons such as Ramadan, Friday giving, Gaza, Al-Quds, Zakat, and Waqf moments.",
    currentPersistence: "foundation repository",
    nextModel: "OperationSeason",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["name", "type", "theme", "startsAt", "endsAt", "hijriDate", "source", "sourceNote", "status", "readiness", "notes"],
    indexes: ["type", "status", "startsAt"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "MonthlyContentPlan",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Stores monthly or seasonal content plans without duplicating Blog, Marketing, or Archive systems.",
    currentPersistence: "foundation repository",
    nextModel: "MonthlyContentPlan",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["title", "month", "seasonId", "theme", "targets", "weeklyThemes", "status", "generatedByAi", "notes"],
    indexes: ["month", "status", "seasonId"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "ContentItem",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Canonical content work item for copy, design, video, SEO, messaging, and archive-sourced content.",
    currentPersistence: "foundation repository",
    nextModel: "ContentItem",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["planId", "title", "theme", "format", "primaryLocale", "targetLocales", "proposedCopy", "copyByLocale", "seo", "relatedPostId", "relatedCampaignIds", "sourceType", "sourceAssetId", "assignedTo", "dueAt", "publishAt", "status", "progress", "reviewStatus"],
    indexes: ["planId", "format", "status", "assignedTo", "dueAt", "publishAt"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "OperationTask",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Single task system for content, translation, design, publishing, archive review, brand work, and donor follow-up.",
    currentPersistence: "foundation repository",
    nextModel: "OperationTask",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["title", "description", "taskType", "status", "priority", "assignedTo", "contentItemId", "planId", "seasonId", "dueAt", "startedAt", "reviewRequestedAt", "completedAt", "approvedAt", "blockedReason", "qualityRating", "workloadScore", "resultNotes"],
    indexes: ["status", "taskType", "assignedTo", "contentItemId", "dueAt"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations/tasks",
  },
  {
    name: "ContentPublication",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Per-platform publishing checklist for a ContentItem, with manual status tracking only.",
    currentPersistence: "foundation repository",
    nextModel: "ContentPublication",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["contentItemId", "platform", "status", "publishedUrl", "scheduledAt", "publishedAt", "checkedBy", "notes"],
    indexes: ["contentItemId + platform", "platform + status", "scheduledAt"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "MessageSchedule",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Manual-first schedule for WhatsApp, Email, SMS, team reminders, publishing reminders, and donor reactivation.",
    currentPersistence: "foundation repository",
    nextModel: "MessageSchedule",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["title", "channel", "scheduleType", "templateId", "contentItemId", "donorReminderId", "status", "scheduledAt", "sentAt", "manuallySentAt", "cancelledAt", "recipientQuery", "notes"],
    indexes: ["channel + status", "scheduleType", "scheduledAt"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations/scheduler",
  },
  {
    name: "DonorReactivationReminder",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Tracks safe donor reactivation candidates and manual follow-up decisions without automatic sending.",
    currentPersistence: "foundation repository",
    nextModel: "DonorReactivationReminder",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["donorId", "lastDonationId", "channel", "locale", "status", "reason", "assignedTo", "dueAt", "sentMessageId", "manuallySentAt", "skippedAt", "dismissedAt", "notes"],
    indexes: ["donorId + status", "channel + status", "dueAt"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "MarketingLearning",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Stores learnings from content and marketing results while reading performance from existing Marketing snapshots.",
    currentPersistence: "foundation repository",
    nextModel: "MarketingLearning",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["title", "source", "summary", "relatedContentId", "relatedCampaignId", "relatedAdId", "impact", "action", "status"],
    indexes: ["source", "status", "relatedContentId"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "ContentAdLink",
    context: "operations",
    status: "PRISMA_READY",
    purpose: "Lightweight bridge from ContentItem to existing campaign/ad identifiers without creating duplicate ad performance tables.",
    currentPersistence: "foundation repository",
    nextModel: "ContentAdLink",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["contentItemId", "platform", "campaignId", "adGroupId", "adId", "snapshotType", "notes"],
    indexes: ["contentItemId", "platform + campaignId", "adId"],
    safety: operationsSafety,
    repositoryOwner: "lib/operations",
  },
  {
    name: "ArchiveCollection",
    context: "archive",
    status: "PRISMA_READY",
    purpose: "Groups operational archive material by theme, geography, year, or campaign season.",
    currentPersistence: "foundation repository",
    nextModel: "ArchiveCollection",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["name", "slug", "type", "description", "order", "isActive"],
    indexes: ["slug", "type", "isActive", "order"],
    safety: archiveSafety,
    repositoryOwner: "lib/archive",
  },
  {
    name: "ArchiveProject",
    context: "archive",
    status: "PRISMA_READY",
    purpose: "Represents a field documentation project connected to collections and Drive links.",
    currentPersistence: "foundation repository",
    nextModel: "ArchiveProject",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["collectionId", "title", "year", "country", "city", "theme", "projectType", "description", "implementationDate", "startDate", "endDate", "status", "documentationStatus", "marketingStatus", "notes"],
    indexes: ["collectionId", "year", "country", "status", "documentationStatus", "marketingStatus"],
    safety: archiveSafety,
    repositoryOwner: "lib/archive",
  },
  {
    name: "ArchiveDriveLink",
    context: "archive",
    status: "PRISMA_READY",
    purpose: "Stores Google Drive folder/file references and sync metadata; sync reads metadata only.",
    currentPersistence: "foundation repository",
    nextModel: "ArchiveDriveLink",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["projectId", "title", "driveUrl", "driveFolderId", "driveFileId", "sharedDriveId", "linkType", "syncStatus", "lastSyncedAt", "lastError", "totalFiles", "totalImages", "totalVideos", "totalOther"],
    indexes: ["projectId", "driveFolderId", "driveFileId", "syncStatus"],
    safety: archiveSafety,
    repositoryOwner: "lib/archive",
  },
  {
    name: "ArchiveAsset",
    context: "archive",
    status: "PRISMA_READY",
    purpose: "Stores Drive file metadata, review signals, AI draft analysis, and marketing/documentation approvals.",
    currentPersistence: "foundation repository",
    nextModel: "ArchiveAsset",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["projectId", "driveLinkId", "googleFileId", "googleFolderId", "fileName", "mimeType", "fileType", "webViewLink", "webContentLink", "thumbnailLink", "previewUrl", "sizeBytes", "aiStatus", "humanReviewStatus", "marketingApproved", "documentationApproved", "tags", "aiSummary", "aiWarnings", "recommendedUse", "marketingScore", "qualityScore", "emotionScore", "clarityScore", "sensitivityScore", "hasChildren", "hasFaces", "needsBlur", "isSensitive", "reviewedBy", "reviewedAt", "reviewerNote"],
    indexes: ["projectId", "driveLinkId", "googleFileId", "fileType", "aiStatus", "humanReviewStatus", "marketingApproved", "documentationApproved", "recommendedUse"],
    safety: archiveSafety,
    repositoryOwner: "lib/archive",
  },
  {
    name: "ArchiveVideoFrame",
    context: "archive",
    status: "PRISMA_READY",
    purpose: "Stores extracted video frame metadata so frames can be reviewed without sending full videos to AI.",
    currentPersistence: "foundation repository",
    nextModel: "ArchiveVideoFrame",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["assetId", "timestampSec", "frameUrl", "thumbnailUrl", "aiSummary", "recommendedUse", "marketingScore", "tags", "needsBlur", "isSensitive"],
    indexes: ["assetId", "timestampSec", "recommendedUse"],
    safety: archiveSafety,
    repositoryOwner: "lib/archive",
  },
  {
    name: "BrandProfile",
    context: "brand",
    status: "PRISMA_READY",
    purpose: "Stores one or more official brand identities such as Gozbebekleri, Minber-i Aksa, and Burak.",
    currentPersistence: "foundation repository",
    nextModel: "BrandProfile",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["name", "description", "mission", "vision", "contentVoice", "messagePhilosophy", "isActive"],
    indexes: ["name", "isActive"],
    safety: brandSafety,
    repositoryOwner: "lib/brand",
  },
  {
    name: "BrandAsset",
    context: "brand",
    status: "PRISMA_READY",
    purpose: "Stores official logos, icons, certificates, templates, watermarks, and intro/outro files separate from ArchiveAsset.",
    currentPersistence: "foundation repository",
    nextModel: "BrandAsset",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["profileId", "title", "type", "format", "fileUrl", "previewUrl", "usage", "locale", "notes", "downloadable"],
    indexes: ["profileId", "type", "downloadable"],
    safety: brandSafety,
    repositoryOwner: "lib/brand",
  },
  {
    name: "BrandColor",
    context: "brand",
    status: "PRISMA_READY",
    purpose: "Stores approved brand colors with usage rules for UI, CTA, certificates, and content design.",
    currentPersistence: "foundation repository",
    nextModel: "BrandColor",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["profileId", "name", "hex", "rgb", "usage", "description", "order"],
    indexes: ["profileId", "hex", "order"],
    safety: brandSafety,
    repositoryOwner: "lib/brand",
  },
  {
    name: "BrandFont",
    context: "brand",
    status: "PRISMA_READY",
    purpose: "Stores typography guidance, fallback stacks, source notes, and usage contexts.",
    currentPersistence: "foundation repository",
    nextModel: "BrandFont",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["profileId", "name", "usage", "fallback", "source", "notes"],
    indexes: ["profileId", "usage"],
    safety: brandSafety,
    repositoryOwner: "lib/brand",
  },
  {
    name: "BrandGuideline",
    context: "brand",
    status: "PRISMA_READY",
    purpose: "Stores voice, copy, dignity, proof, CTA, and localization rules for writers and AI draft checks.",
    currentPersistence: "foundation repository",
    nextModel: "BrandGuideline",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["profileId", "section", "title", "body", "examples", "order"],
    indexes: ["profileId", "section", "order"],
    safety: brandSafety,
    repositoryOwner: "lib/brand",
  },
  {
    name: "BrandMessageFramework",
    context: "brand",
    status: "PRISMA_READY",
    purpose: "Stores reusable message structures for Friday, Zakat, Waqf, emergency, thank-you, Ramadan, and donor reactivation copy.",
    currentPersistence: "foundation repository",
    nextModel: "BrandMessageFramework",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["profileId", "name", "type", "locale", "structure", "sampleText", "doList", "dontList"],
    indexes: ["profileId", "type", "locale"],
    safety: brandSafety,
    repositoryOwner: "lib/brand",
  },
  {
    name: "AiOperationRun",
    context: "ai",
    status: "PRISMA_READY",
    purpose: "Audit foundation for AI prompts, requested tools, context, draft output, status, and human approval metadata.",
    currentPersistence: "audit foundation",
    nextModel: "AiOperationRun",
    readyForPrisma: true,
    migrationRisk: "LOW",
    fields: ["context", "prompt", "requestedTool", "status", "output", "approvedBy", "approvedAt", "createdBy", "createdAt"],
    indexes: ["context + createdAt", "status"],
    safety: aiSafety,
    repositoryOwner: "lib/ai/core",
  },
];

const contextOrder: DashboardDbContractContext[] = ["operations", "archive", "brand", "ai"];

export function getDashboardDbContractsSnapshot() {
  const byContext = contextOrder.map((context) => {
    const contracts = dashboardDbContracts.filter((contract) => contract.context === context);
    return {
      context,
      total: contracts.length,
      prismaReady: contracts.filter((contract) => contract.readyForPrisma).length,
      dbBacked: contracts.filter((contract) => contract.status === "DB_BACKED").length,
      contracts,
    };
  });

  return {
    generatedAt: new Date().toISOString(),
    summary: {
      totalModels: dashboardDbContracts.length,
      prismaReadyModels: dashboardDbContracts.filter((contract) => contract.readyForPrisma).length,
      dbBackedModels: dashboardDbContracts.filter((contract) => contract.status === "DB_BACKED").length,
      foundationModels: dashboardDbContracts.filter((contract) => contract.status === "FOUNDATION").length,
      lowRiskModels: dashboardDbContracts.filter((contract) => contract.migrationRisk === "LOW").length,
    },
    byContext,
    contracts: dashboardDbContracts,
    safetyRules: [
      "No payment runtime changes",
      "No tracking runtime changes",
      "No external platform calls",
      "No frontend secrets",
      "No automatic sending or publishing",
      "Human approval remains required for AI, archive, and outbound actions",
    ],
    nextRecommendedPackage: {
      title: "Prisma Model Migration and Repository Cutover",
      scope: "Add the stable Prisma models, run prisma generate/build, then move one repository at a time from foundation data to DB-backed data.",
      firstSlice: ["BrandProfile", "BrandColor", "BrandGuideline", "ArchiveCollection", "ArchiveProject", "OperationTask"],
    },
  };
}
