"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { funds, reels } from "@/data/homepage";

type Intent = { label:string; kind:"zakat"|"waqf"|"urgent"|"general" };
const intents:Intent[]=[{label:"زكاة",kind:"zakat"},{label:"وقف",kind:"waqf"},{label:"غزة",kind:"urgent"},{label:"الأقصى",kind:"general"},{label:"القدس",kind:"general"},{label:"حيث الحاجة أشد",kind:"general"},{label:"عطاء مستمر",kind:"general"}];
const frequencies=["مرة واحدة","كل جمعة","شهري"];
const amounts=[100,250,500,1000];

export function QuickDonation(){
 const [intent,setIntent]=useState(intents[5]),[frequency,setFrequency]=useState(frequencies[0]),[amount,setAmount]=useState(250),[custom,setCustom]=useState(""),[toast,setToast]=useState(false); const selected=custom?Math.max(0,Number(custom)||0):amount;
 const add=()=>{window.dispatchEvent(new CustomEvent("minber:add-to-basket",{detail:{intent:intent.kind,intentLabel:intent.label,project:intent.label==="حيث الحاجة أشد"?"حيث الحاجة أشد":`عطاء: ${intent.label}`,amount:selected,currency:"USD"}}));setToast(true);window.setTimeout(()=>setToast(false),2200)};
 return <section className="home-section quick-donation" id="donate" aria-labelledby="quick-title"><div className="site-container"><div className="section-heading-row"><div><span className="section-eyebrow">تبرع سريع</span><h2 id="quick-title">اختر نيتك ومبلغك في خطوة واحدة</h2><p>حدّد نوع عطائك ودوريته ومبلغه، ثم أضفه إلى سلة العطاء أو أكمل التبرع.</p></div></div><div className="quick-grid"><div className="quick-controls"><fieldset><legend>نية العطاء</legend><div className="choice-wrap">{intents.map(x=><button type="button" key={x.label} className={intent.label===x.label?"choice is-selected":"choice"} aria-pressed={intent.label===x.label} onClick={()=>setIntent(x)}>{x.label}</button>)}</div></fieldset><fieldset><legend>الدورية</legend><div className="choice-wrap">{frequencies.map(x=><button type="button" key={x} className={frequency===x?"choice is-selected":"choice"} aria-pressed={frequency===x} onClick={()=>setFrequency(x)}>{x}</button>)}</div></fieldset><fieldset><legend>المبلغ · USD</legend><div className="choice-wrap amount-choices">{amounts.map(x=><button type="button" key={x} className={!custom&&amount===x?"choice is-selected":"choice"} aria-pressed={!custom&&amount===x} onClick={()=>{setAmount(x);setCustom("")}}>{x}</button>)}<label className="custom-amount"><span>مبلغ آخر</span><input inputMode="decimal" value={custom} onChange={e=>setCustom(e.target.value)} aria-label="مبلغ آخر بالدولار" /></label></div></fieldset></div><aside className="donation-summary" aria-live="polite"><span>ملخص عطائك</span><dl><div><dt>نيتك</dt><dd>{intent.label}</dd></div><div><dt>الدورية</dt><dd>{frequency}</dd></div><div><dt>المبلغ</dt><dd>{selected} USD</dd></div></dl><p>سيُوجّه تبرعك إلى أكثر الاحتياجات إلحاحًا ضمن مشاريع القدس وغزة.</p><Button fullWidth>تبرع بأمان</Button><Button variant="outline" fullWidth onClick={add} disabled={selected<=0}>أضف إلى سلة العطاء</Button></aside></div><div className={toast?"toast is-visible":"toast"} role="status" aria-live="polite">تمت إضافة عطائك إلى السلة</div></div></section>
}

export function FundsSelector(){const [active,setActive]=useState<(typeof funds)[number]>(funds[0]);return <div className="funds-layout"><div className={`fund-feature fund-feature--${active.tone}`}><span>{active.kind}</span><h3>{active.title}</h3><p>{active.description}</p><Button href="#donate" variant="outline">ساهم في هذا المسار</Button></div><div className="fund-list" role="list">{funds.map(f=><button type="button" role="listitem" key={f.id} className={active.id===f.id?"fund-row is-selected":"fund-row"} onClick={()=>setActive(f)} aria-pressed={active.id===f.id}><span>{f.kind}</span><strong>{f.title}</strong><small>{f.description}</small></button>)}</div></div>}

export function ZakatCalculator(){const [cash,setCash]=useState(""),[gold,setGold]=useState(""),[trade,setTrade]=useState(""),[debts,setDebts]=useState(""),[calculated,setCalculated]=useState(false),[notice,setNotice]=useState(false);const base=Math.max(0,[cash,gold,trade].reduce((s,x)=>s+(Number(x)||0),0)-(Number(debts)||0)),zakat=calculated?base*.025:0;const fields:[string,string,(v:string)=>void][]=[["النقد والمدخرات",cash,setCash],["الذهب والفضة",gold,setGold],["الاستثمارات والتجارة",trade,setTrade],["الالتزامات قصيرة الأجل",debts,setDebts]];return <div className="zakat-tool"><div className="zakat-fields">{fields.map(([label,value,setter])=><label key={label}><span>{label}</span><div><input inputMode="decimal" value={value} onChange={e=>setter(e.target.value)} /><b>USD</b></div></label>)}</div><aside className="zakat-result"><small>Prototype calculation only</small><dl><div><dt>المال الزكوي</dt><dd>{base.toFixed(2)} USD</dd></div><div><dt>مقدار الزكاة</dt><dd>{zakat.toFixed(2)} USD</dd></div></dl><label className="check-row"><input type="checkbox" /><span>أنوي هذا المبلغ زكاة</span></label><Button fullWidth onClick={()=>setCalculated(true)}>احسب زكاتك</Button><Button type="button" variant="text" onClick={()=>setNotice(true)}>انتقل إلى صفحة الزكاة</Button>{notice?<p className="prototype-notice" role="status">صفحة الزكاة الكاملة ستُنفذ في مرحلة مستقلة.</p>:null}</aside></div>}

export function WaqfBuilder(){const [type,setType]=useState("سهم وقفي"),[name,setName]=useState("اسم تجريبي"),[amount,setAmount]=useState(250),[notice,setNotice]=useState(false);return <div className="waqf-layout"><div className="waqf-controls"><div className="choice-wrap">{["سهم وقفي","مساهمة مفتوحة","إهداء وقف"].map(x=><button type="button" key={x} className={type===x?"choice is-selected":"choice"} onClick={()=>setType(x)} aria-pressed={type===x}>{x}</button>)}</div><label><span>المبلغ التجريبي</span><input type="number" min="1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><label><span>اسم المتبرع أو المهدى إليه</span><input value={name} onChange={e=>setName(e.target.value)}/></label><p className="helper">الأرقام والنماذج المعروضة تحتاج اعتماد الإدارة قبل الإطلاق.</p><Button>أنشئ وقفًا</Button></div><div className="certificate-preview" aria-label="معاينة شهادة وقف"><span className="certificate-line"/><small>معاينة شهادة وقف</small><div className="certificate-logo">OFFICIAL LOGO REQUIRED</div><p>تشهد مؤسسة منبر الأقصى الدولية بأن</p><h3>{name||"اسم تجريبي"}</h3><p>ساهم في: <strong>{type}</strong></p><b>{amount} USD</b><code>PREVIEW-WAQF-0001</code><Button type="button" variant="outline" size="small" onClick={()=>setNotice(true)}>معاينة الشهادة</Button>{notice?<small className="prototype-notice" role="status">هذه معاينة Frontend فقط، ولا يتم إنشاء PDF.</small>:null}</div></div>}

const recurringOptions={"يومي":[10,25,50],"كل جمعة":[50,100,250],"شهري":[250,500,1000]} as const;
export function RecurringGivingTool(){const [frequency,setFrequency]=useState<keyof typeof recurringOptions>("كل جمعة"),[amount,setAmount]=useState(100);const options=recurringOptions[frequency];return <div className="recurring-tool"><div><div className="choice-wrap">{Object.keys(recurringOptions).map(x=><button type="button" key={x} className={frequency===x?"choice is-selected":"choice"} aria-pressed={frequency===x} onClick={()=>{const f=x as keyof typeof recurringOptions;setFrequency(f);setAmount(recurringOptions[f][1])}}>{x}</button>)}</div><div className="recurring-amounts">{options.map(x=><button type="button" key={x} className={amount===x?"is-selected":""} aria-pressed={amount===x} onClick={()=>setAmount(x)}><strong>{x}</strong><span>USD</span></button>)}</div></div><aside><span>اختيارك</span><strong>{amount} USD</strong><p>{frequency}</p><ul><li>يمكن الإيقاف في أي وقت</li><li>إيصال مع كل عملية</li><li>تحديثات أثر</li></ul><Button fullWidth>فعّل عطاءً مستمرًا</Button></aside></div>}

export function ReelsExperience(){const [active,setActive]=useState(0),[notice,setNotice]=useState(false);const reel=reels[active];return <div className="reels-layout"><div className="featured-reel"><div className="reel-poster"><span>APPROVED VIDEO POSTER REQUIRED</span><button type="button" aria-label={`تشغيل ${reel[0]}`} onClick={()=>setNotice(true)}>▶</button></div><div><span>{reel[1]} · {reel[2]}</span><h3>{reel[0]}</h3><p>معاينة Frontend لفيديو ميداني معتمد من أنشطة المؤسسة.</p><Button type="button" variant="outline" onClick={()=>setNotice(true)}>شاهد الفيديو</Button><Button href="#donate" variant="text">ادعم هذا المشروع</Button>{notice?<small className="prototype-notice" role="status">مشغل الفيديو الكامل سيُنفذ لاحقًا بعد اعتماد الأصل الرسمي.</small>:null}</div></div><div className="reel-strip">{reels.map((x,i)=><button type="button" key={x[0]} className={i===active?"reel-card is-selected":"reel-card"} onClick={()=>{setActive(i);setNotice(false)}} aria-pressed={i===active}><span className="mini-poster">▶</span><small>{x[1]} · {x[2]}</small><strong>{x[0]}</strong></button>)}</div></div>}
