import { ProjectFaq } from "@/components/project-detail/project-faq";
import { AlQudsGoldCoin } from "@/components/brand/al-quds-gold-coin";
import { GoldenIdentityPattern } from "@/components/brand/golden-identity-pattern";
import { WaqfCertificateShowcase } from "@/components/documents/waqf-certificate-showcase";
import { Button } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import type { ProjectRecord, ProjectRegion, ProjectStatus } from "@/data/projects";
import { waqfDedicationExamples, waqfFaqs, waqfPrinciples, waqfRecordFields, waqfReportingItems } from "@/data/waqf";
import { WaqfBuilder } from "./waqf-builder";

const regions: Record<ProjectRegion, string> = { "al-quds": "القدس", "al-aqsa": "الأقصى", gaza: "غزة", syria: "سوريا", sudan: "السودان", yemen: "اليمن", global: "عام" };
const statuses: Record<ProjectStatus, string> = { active: "نشط", seasonal: "موسمي", archived: "مكتمل", "needs-verification": "قيد التحقق" };
const journey = ["إنشاء الوقف", "تسجيل صاحب الوقف", "إصدار الشهادة", "ربطه بالمشروع", "تحديثات التنفيذ", "التقرير الدوري"];
function Media({ project, big = false }: { project: ProjectRecord; big?: boolean }) { return project.image ? <figure className={big ? "w-project-media big" : "w-project-media"}><img src={project.image.sourceUrl} alt={project.image.alt.ar} /><figcaption>Temporary source · final approval required</figcaption></figure> : <div className={big ? "w-placeholder big" : "w-placeholder"}><strong>APPROVED AL-QUDS WAQF IMAGE REQUIRED</strong><span>Verified project context · Human activity · No AI</span></div>; }

export function WaqfPageSections({ projects }: { projects: ProjectRecord[] }) {
  const featured = projects.find((project) => project.featured) || projects[0];
  const secondary = projects.filter((project) => project.id !== featured?.id).slice(0, 2);
  const choices = projects.map((project) => ({ id: project.id, slug: project.slug, title: project.title.ar }));
  return <>
    <div className="w-breadcrumb"><Container><nav aria-label="مسار التنقل"><a href="/">الرئيسية</a><span>←</span><span aria-current="page">الوقف</span></nav></Container></div>
    <section className="w-hero w-hero--golden" aria-labelledby="w-hero-title"><GoldenIdentityPattern /><Container><div className="w-hero-copy"><span>وقف القدس · أثر ممتد</span><h1 id="w-hero-title">التعريف بمشروعنا الوقفي لدعم القدس والأقصى</h1><p>أنشئ مساهمة وقفية مرتبطة بمشروع معتمد، وسجّل اسم صاحب الوقف، ثم تابع الشهادة وتحديثات التنفيذ ضمن تجربة واضحة لا تدّعي عائدًا ماليًا.</p><div><Button href="#waqf-builder" size="large">أنشئ وقفًا</Button><Button href="#waqf-certificate" variant="outline" size="large">شاهد نموذج الشهادة</Button><Button href="#waqf-journey" variant="text">كيف يعمل الوقف؟</Button></div><ul><li>مساهمة موثقة</li><li>شهادة وقف</li><li>تقارير دورية</li><li>أثر ممتد</li></ul></div><div className="w-hero-media w-hero-media--gold"><div className="w-placeholder big"><strong>APPROVED AL-QUDS WAQF HERO REQUIRED</strong><span>Official project or property context · Independent mobile crop</span><small>No AI · No tourism imagery</small></div><AlQudsGoldCoin decorative /></div></Container></section>
    <section className="w-video"><Container><div className="w-video-placeholder" role="img" aria-label="مكان الفيديو التعريفي الرسمي"><span>OFFICIAL WAQF VIDEO REQUIRED</span><strong>فيديو تعريفي رسمي بالمشروع الوقفي</strong><p>لا يتم تشغيل فيديو أو استخدام Poster غير مسجل حتى اعتماد الرابط والأصل الرسمي.</p></div><div><span>التعريف بالمشروع</span><h2>كيف يتحول الوقف إلى منفعة مستمرة؟</h2><p>يعرض الفيديو الرسمي لاحقًا طبيعة المشروع ومراحل التنفيذ والتوثيق، دون وعود استثمارية أو أرباح للمتبرع.</p></div></Container></section>
    <section className="w-what"><Container><div><span>المعنى العملي</span><h2>وقف اليوم<br />أثر يمتد لسنوات</h2><p>الوقف دعم طويل المدى يرتبط بأصل أو مشروع يخدم الغرض المعتمد. لا يمثل استثمارًا شخصيًا ولا يحقق عائدًا ماليًا للمتبرع.</p><aside>التفاصيل القانونية والتشغيلية لكل مشروع تحتاج اعتماد المؤسسة قبل الإطلاق.</aside></div><div className="w-principles">{waqfPrinciples.map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></Container></section>
    <Container><WaqfBuilder projects={choices} /></Container>
    <section id="waqf-certificate" className="w-certificate-section"><Container><WaqfCertificateShowcase /></Container></section>
    <section className="w-cycle w-cycle--journey" id="waqf-journey"><Container><header><span>رحلة التوثيق والأثر</span><h2>من إنشاء الوقف إلى التقرير الدوري</h2><p>كل مرحلة تبقى بحالتها الفعلية، ولا تُعرض شهادة أو وثيقة نهائية قبل الدفع والمراجعة.</p></header><ol>{journey.map((title, index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{index === 0 ? "اختيار نوع الوقف والمشروع والمبلغ المعتمد." : index === 1 ? "تسجيل الاسم والإهداء داخل عنصر الوقف." : index === 2 ? "تظل الشهادة معاينة حتى الإصدار الحقيقي." : index === 3 ? "ربط المساهمة بمشروع يقبل waqf فقط." : index === 4 ? "عرض التحديثات بعد التحقق من التنفيذ." : "إضافة التقرير والوثائق بعد اعتمادها."}</p></div></li>)}</ol></Container></section>
    <section className="w-projects" id="waqf-projects"><Container><header><span>مجالات المشروع الوقفي</span><h2>مشاريع وقف رسمية</h2><p>تعرض الصفحة فقط المشاريع التي تحتوي على نوع العطاء waqf، دون باقات متجر أو أسعار مختلقة.</p></header>{featured ? <div className="w-project-showcase"><article className="w-featured"><Media project={featured} big /><div><small>{regions[featured.region]} · {statuses[featured.status]}</small><h3>{featured.title.ar}</h3><p>{featured.summary.ar}</p><div className="w-status">المرحلة الحالية: بيانات المشروع قيد الاعتماد</div><div className="w-status">التوثيق: {featured.image ? "مصدر مؤقت يحتاج الاعتماد" : "بيانات مطلوبة"}</div><footer><Button href={`/projects/${featured.slug}`} variant="outline">عرض المشروع</Button><Button href="#waqf-builder">ساهم في الوقف</Button></footer></div></article><div className="w-secondary">{secondary.map((project) => <article key={project.id}><Media project={project} /><div><small>{regions[project.region]} · {statuses[project.status]}</small><h3>{project.title.ar}</h3><p>{project.summary.ar}</p><Button href={`/projects/${project.slug}`} variant="outline" size="small">عرض المشروع</Button></div></article>)}</div></div> : <div className="w-empty">مشاريع وقفية إضافية قيد الاعتماد</div>}</Container></section>
    <section className="w-record"><Container><div className="w-record-intro"><span>Impact Record</span><h2>سجل واضح لمشروع الوقف</h2><p>نموذج مؤسسي لعرض هوية المشروع ووثائقه دون مظهر مالي أو استثماري.</p></div><article><header><small>PROJECT PASSPORT</small><h3>{featured?.title.ar || "مشروع وقفي قيد الاعتماد"}</h3><p>{featured ? regions[featured.region] : "القدس"} · {featured ? statuses[featured.status] : "بيانات مطلوبة"}</p></header><dl><div><dt>نوع المشروع</dt><dd>{featured?.tags.slice(0, 2).join(" · ") || "بيانات مطلوبة"}</dd></div><div><dt>المرحلة الحالية</dt><dd>قيد الاعتماد</dd></div>{waqfRecordFields.map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></article></Container></section>
    <section className="w-reporting"><Container><header><span>الاستمرارية</span><h2>تابع وقفك مع مرور الوقت</h2><p>لا توجد عوائد أو أرباح؛ المتابعة مرتبطة بالمشروع والمنفعة والوثائق.</p></header><div>{waqfReportingItems.map(([title, status], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><strong>{status}</strong></article>)}</div></Container></section>
    <section className="w-dedication"><Container><header><span>تجربة إنسانية</span><h2>وقف باسم من تحب</h2><p>الأمثلة لا تستخدم بيانات أشخاص حقيقيين، وتبقى الشهادة معاينة حتى الدفع والاعتماد.</p></header><div>{waqfDedicationExamples.map(([title, description]) => <article key={title}><h3>{title}</h3><p>{description}</p><strong>اسم صاحب الوقف</strong></article>)}</div></Container></section>
    <section className="w-faq"><Container><header><span>قبل إنشاء الوقف</span><h2>الأسئلة الشائعة</h2></header><ProjectFaq items={[...waqfFaqs]} /></Container></section>
    <section className="w-final"><Container><div><span>مساهمة موثقة · مشروع معتمد · متابعة دورية</span><h2>اربط مساهمتك بمشروع وقف رسمي</h2><p>اختر المشروع وصاحب الوقف وشاهد معاينة الشهادة دون أي عائد أو سعر غير معتمد.</p></div><Button href="#waqf-builder" size="large">أنشئ وقفًا</Button></Container></section>
  </>;
}
