import {ProjectFaq} from "@/components/project-detail/project-faq";
import {Button} from "@/components/ui/button";
import {Container} from "@/components/ui/container";
import type {ProjectRecord,ProjectRegion,ProjectStatus} from "@/data/projects";
import {waqfDedicationExamples,waqfFaqs,waqfImpactCycle,waqfPrinciples,waqfRecordFields,waqfReportingItems} from "@/data/waqf";
import {WaqfBuilder} from "./waqf-builder";
const R:Record<ProjectRegion,string>={"al-quds":"القدس","al-aqsa":"الأقصى",gaza:"غزة",syria:"سوريا",sudan:"السودان",yemen:"اليمن",global:"عام"};
const S:Record<ProjectStatus,string>={active:"نشط",seasonal:"موسمي",archived:"مكتمل","needs-verification":"قيد التحقق"};
function Media({p,big=false}:{p:ProjectRecord;big?:boolean}){return p.image?<figure className={big?"w-project-media big":"w-project-media"}><img src={p.image.sourceUrl} alt={p.image.alt.ar}/><figcaption>Temporary source · final project relation required</figcaption></figure>:<div className={big?"w-placeholder big":"w-placeholder"}><strong>APPROVED AL-QUDS WAQF IMAGE REQUIRED</strong><span>Verified project or property context · Human activity visible · No AI · No tourism imagery</span></div>}
export function WaqfPageSections({projects}:{projects:ProjectRecord[]}){const featured=projects.find(p=>p.featured)||projects[0],secondary=projects.filter(p=>p.id!==featured?.id).slice(0,2),choices=projects.map(p=>({id:p.id,slug:p.slug,title:p.title.ar}));return <>
<div className="w-breadcrumb"><Container><nav aria-label="مسار التنقل"><a href="/">الرئيسية</a><span>←</span><span aria-current="page">الوقف</span></nav></Container></div>
<section className="w-hero" aria-labelledby="w-hero-title"><Container><div className="w-hero-copy"><span>وقف القدس · أثر ممتد</span><h1 id="w-hero-title">اجعل لك وقفًا باقيًا في القدس</h1><p>ساهم في مشروع وقفي يخدم أهل القدس على المدى الطويل، واختر اسم صاحب الوقف، وشاهد كيف يتم توثيق المشروع واستمرار أثره.</p><div><Button href="#waqf-builder" size="large">أنشئ وقفًا</Button><Button href="#waqf-projects" variant="outline" size="large">استكشف مشاريع الوقف</Button><Button href="#waqf-cycle" variant="text">كيف يعمل الوقف؟</Button></div><ul><li>مساهمة موثقة</li><li>شهادة وقف</li><li>تقارير دورية</li><li>أثر ممتد</li></ul></div><div className="w-hero-media"><div className="w-placeholder big"><strong>APPROVED AL-QUDS WAQF IMAGE REQUIRED</strong><span>Verified project context · Human activity · Minimum 2400 × 1600 · Independent mobile crop</span><small>No AI · No tourism imagery · No decorative architecture only</small></div></div></Container><div className="w-signature"><Container>{["مساهمتك","مشروع أو أصل وقفي","منفعة مستمرة","دعم أهل القدس","تقرير وأثر متجدد"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</Container></div></section>
<section className="w-what"><Container><div><span>المعنى العملي</span><h2>وقف اليوم<br/>أثر يمتد لسنوات</h2><p>الوقف دعم طويل المدى يرتبط بأصل أو مشروع يخدم الغرض المعتمد. لا يمثل استثمارًا شخصيًا ولا يحقق عائدًا ماليًا للمتبرع.</p><aside>التفاصيل القانونية والتشغيلية لكل مشروع تحتاج اعتماد المؤسسة قبل الإطلاق.</aside></div><div className="w-principles">{waqfPrinciples.map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></Container></section>
<Container><WaqfBuilder projects={choices}/></Container>
<section className="w-cycle" id="waqf-cycle"><Container><header><span>رحلة الأثر</span><h2>كيف يمتد أثر وقفك؟</h2><p>كل مرحلة تحتاج ملف مشروع وتوثيقًا قبل اعتبارها مكتملة.</p></header><ol>{waqfImpactCycle.map(([n,t,d])=><li key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></li>)}</ol></Container></section>
<section className="w-projects" id="waqf-projects"><Container><header><span>من data/projects.ts</span><h2>مشاريع وقف رسمية</h2><p>تعرض الصفحة فقط المشاريع التي تحتوي على نوع العطاء waqf.</p></header>{featured?<div className="w-project-showcase"><article className="w-featured"><Media p={featured} big/><div><small>{R[featured.region]} · {S[featured.status]}</small><h3>{featured.title.ar}</h3><p>{featured.summary.ar}</p><div className="w-status">المرحلة الحالية: بيانات المشروع قيد الاعتماد</div><div className="w-status">التوثيق: {featured.image?"مصدر مؤقت يحتاج الاعتماد":"بيانات مطلوبة"}</div><footer><Button href={`/projects/${featured.slug}`} variant="outline">عرض المشروع</Button><Button href="#waqf-builder">ساهم في الوقف</Button></footer></div></article><div className="w-secondary">{secondary.map(p=><article key={p.id}><Media p={p}/><div><small>{R[p.region]} · {S[p.status]}</small><h3>{p.title.ar}</h3><p>{p.summary.ar}</p><Button href={`/projects/${p.slug}`} variant="outline" size="small">عرض المشروع</Button></div></article>)}</div></div>:<div className="w-empty">مشاريع وقفية إضافية قيد الاعتماد</div>}</Container></section>
<section className="w-record"><Container><div className="w-record-intro"><span>Impact Record</span><h2>سجل واضح لمشروع الوقف</h2><p>نموذج مؤسسي لعرض هوية المشروع ووثائقه دون مظهر مالي أو استثماري.</p></div><article><header><small>PROJECT PASSPORT</small><h3>{featured?.title.ar||"مشروع وقفي قيد الاعتماد"}</h3><p>{featured?R[featured.region]:"القدس"} · {featured?S[featured.status]:"بيانات مطلوبة"}</p></header><dl><div><dt>نوع المشروع</dt><dd>{featured?.tags.slice(0,2).join(" · ")||"بيانات مطلوبة"}</dd></div><div><dt>المرحلة الحالية</dt><dd>قيد الاعتماد</dd></div>{waqfRecordFields.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></article></Container></section>
<section className="w-reporting"><Container><header><span>الاستمرارية</span><h2>تابع وقفك مع مرور الوقت</h2><p>لا توجد عوائد أو أرباح أو Performance Charts؛ المتابعة مرتبطة بالمشروع والمنفعة والوثائق.</p></header><div>{waqfReportingItems.map(([t,s],i)=><article key={t}><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><strong>{s}</strong></article>)}</div></Container></section>
<section className="w-dedication"><Container><header><span>تجربة إنسانية</span><h2>وقف باسم من تحب</h2><p>الأمثلة لا تستخدم بيانات أشخاص حقيقيين، وتبقى الشهادة معاينة حتى الدفع والاعتماد.</p></header><div>{waqfDedicationExamples.map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p><strong>اسم صاحب الوقف</strong></article>)}</div></Container></section>
<section className="w-faq"><Container><header><span>قبل إنشاء الوقف</span><h2>الأسئلة الشائعة</h2></header><ProjectFaq items={[...waqfFaqs]}/></Container></section>
<section className="w-final"><Container><div><span>أثر يمتد</span><h2>اربط مساهمتك بمشروع وقف رسمي</h2><p>اختر المشروع وصاحب الوقف وشاهد معاينة الشهادة دون أي عائد أو سعر غير معتمد.</p></div><Button href="#waqf-builder" size="large">أنشئ وقفًا</Button></Container></section>
</>}
