"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Button} from "@/components/ui/button";
type Project={id:string;slug:string;title:string};
type WaqfType="share"|"open"|"gift"|"project";
const typeLabels:Record<WaqfType,string>={share:"سهم وقفي",open:"مساهمة مفتوحة",gift:"إهداء وقف",project:"تمويل مشروع أو مرحلة"};
const focusable='button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
const clean=(v:string)=>v.replace(/[^0-9.]/g,"").replace(/(\..*)\./g,"$1");
export function WaqfBuilder({projects}:{projects:Project[]}){
 const [type,setType]=useState<WaqfType>("open"),[projectId,setProjectId]=useState(projects[0]?.id||""),[scope,setScope]=useState("المشروع كاملًا");
 const [amount,setAmount]=useState(250),[custom,setCustom]=useState(""),[units,setUnits]=useState(1),[ownerMode,setOwnerMode]=useState("عني"),[owner,setOwner]=useState(""),[sender,setSender]=useState(""),[occasion,setOccasion]=useState("وقف عام"),[dedication,setDedication]=useState("");
 const [message,setMessage]=useState(""),[toast,setToast]=useState(false),[fileState,setFileState]=useState(false),[sheet,setSheet]=useState(false),[step,setStep]=useState(1);
 const sheetRef=useRef<HTMLElement|null>(null),triggerRef=useRef<HTMLButtonElement|null>(null);
 const selectedProject=projects.find(p=>p.id===projectId),selectedAmount=custom?Number(custom)||0:amount;
 const canAdd=type!=="share"&&selectedAmount>0&&owner.trim().length>0&&(type!=="project"||Boolean(selectedProject));
 const summary=useMemo(()=>({type:typeLabels[type],project:selectedProject?.title||"مشروع وقفي قيد الاختيار",amount:type==="share"?"PRICE DATA REQUIRED":`${selectedAmount.toFixed(2)} USD`,owner:owner||"اسم صاحب الوقف"}),[type,selectedProject,selectedAmount,owner]);
 useEffect(()=>{if(!sheet||!sheetRef.current)return;const old=document.body.style.overflow;document.body.style.overflow="hidden";const root=sheetRef.current;const items=()=>Array.from(root.querySelectorAll<HTMLElement>(focusable));setTimeout(()=>items()[0]?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setSheet(false);if(e.key!=="Tab")return;const a=items(),first=a[0],last=a[a.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener("keydown",key);return()=>{document.body.style.overflow=old;document.removeEventListener("keydown",key);triggerRef.current?.focus()}},[sheet]);
 const changeType=(t:WaqfType)=>{setType(t);setStep(2);setMessage("");if(t==="share")setCustom("")};
 const addBasket=()=>{if(type==="share"){setMessage("قيمة السهم قيد الاعتماد؛ لا يمكن إضافته بقيمة وهمية.");return}if(!canAdd){setMessage("أدخل اسم صاحب الوقف وحدد مبلغًا ومشروعًا صالحًا.");return}window.dispatchEvent(new CustomEvent("minber:add-to-basket",{detail:{intent:"waqf",intentLabel:"وقف",donationMode:type==="gift"?"gift":"one-time",waqfType:type,projectId:selectedProject?.id,slug:selectedProject?.slug,project:selectedProject?.title||typeLabels[type],amount:selectedAmount,currency:"USD",ownerName:owner,dedication,source:"waqf-page",certificateType:"waqf",giftData:type==="gift"?{recipient:owner,occasion,message:dedication,sender}:undefined,dedicationData:{target:ownerMode,ownerName:owner,dedication}}}));setMessage("تمت إضافة الوقف كعنصر مستقل إلى سلة العطاء.");setToast(true);setTimeout(()=>setToast(false),2200)};
 const checkout=()=>setMessage(canAdd?"سيتم الانتقال إلى Checkout بعد ربط نظام الدفع. لا يتم تنفيذ دفع حقيقي الآن.":"أكمل بيانات الوقف أولًا.");
 const certificate=<div className="w-certificate" aria-live="polite"><span className="w-certificate-line"/><small>معاينة شهادة غير نهائية</small><div>OFFICIAL LOGO REQUIRED</div><p>مؤسسة منبر الأقصى الدولية</p><h3>{owner||"اسم صاحب الوقف"}</h3><dl><div><dt>نوع المساهمة</dt><dd>{summary.type}</dd></div><div><dt>المشروع</dt><dd>{summary.project}</dd></div><div><dt>الإهداء</dt><dd>{dedication||"يظهر نص الإهداء هنا"}</dd></div><div><dt>التاريخ</dt><dd>سيُضاف بعد الدفع</dd></div></dl><code>PREVIEW-WAQF-0001</code></div>;
 const builder=<div className="w-builder-body"><nav className="w-builder-steps" aria-label="مراحل إنشاء الوقف">{["نوع الوقف","المشروع أو المبلغ","صاحب الوقف","الشهادة","الملخص"].map((x,i)=><button key={x} aria-pressed={step===i+1} onClick={()=>setStep(i+1)}><b>{i+1}</b>{x}</button>)}</nav>
 <div className={step===1?"w-step active":"w-step"}><fieldset><legend>اختر طريقة مساهمتك الوقفية</legend><div className="w-type-grid">{(Object.keys(typeLabels) as WaqfType[]).map(t=><button key={t} className={type===t?"is-selected":""} aria-pressed={type===t} onClick={()=>changeType(t)}><span>{typeLabels[t]}</span><small>{t==="share"?"السعر قيد الاعتماد":t==="open"?"مبلغ مرن":t==="gift"?"عن شخص عزيز":"مشروع أو مرحلة"}</small></button>)}</div></fieldset></div>
 <div className={step===2?"w-step active":"w-step"}>{type==="share"?<section className="w-price-required"><span>PRICE DATA REQUIRED</span><h3>قيمة السهم الوقفي قيد الاعتماد</h3><p>لا يتم حساب إجمالي مالي من سعر غير موثّق.</p><label><span>عدد الأسهم</span><input type="number" min={1} value={units} onChange={e=>setUnits(Math.max(1,Number(e.target.value)||1))}/></label><Button type="button" variant="outline" onClick={()=>setMessage("تم تسجيل حالة اهتمام تجريبية فقط؛ لا تُرسل بيانات.")}>سجّل اهتمامك</Button></section>:<fieldset><legend>{type==="project"?"اختر المشروع ونطاق التمويل":"اختر مبلغ المساهمة"}</legend>{type==="project"&&<><label><span>المشروع الوقفي</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><div className="w-scope"><button className={scope==="المشروع كاملًا"?"is-selected":""} onClick={()=>setScope("المشروع كاملًا")}>المشروع كاملًا</button><button className={scope==="مرحلة من المشروع"?"is-selected":""} onClick={()=>setScope("مرحلة من المشروع")}>مرحلة من المشروع</button></div><div className="w-file-state"><strong>ملف المشروع مطلوب</strong><p>تفاصيل المرحلة والتكلفة والوثائق تحتاج اعتماد المؤسسة.</p><button onClick={()=>{setFileState(true);setMessage("طلب ملف المشروع Prototype فقط؛ لا يوجد نموذج تواصل أو إرسال.")}}>اطلب ملف المشروع</button>{fileState&&<small>Prototype state active</small>}</div></>}<div className="w-amounts">{[100,250,500,1000].map(v=><button key={v} aria-pressed={!custom&&amount===v} className={!custom&&amount===v?"is-selected":""} onClick={()=>{setAmount(v);setCustom("")}}>{v} USD</button>)}</div><label><span>مبلغ آخر</span><input inputMode="decimal" value={custom} onChange={e=>setCustom(clean(e.target.value))}/></label><small>مبالغ تجريبية لتصميم التجربة</small></fieldset>}<Button type="button" variant="outline" onClick={()=>setStep(3)}>التالي</Button></div>
 <div className={step===3?"w-step active":"w-step"}><fieldset><legend>صاحب الوقف والإهداء</legend><div className="w-owner-modes">{["عني","عن شخص آخر","عن الوالدين","عن متوفى","وقف عائلي"].map(x=><button key={x} className={ownerMode===x?"is-selected":""} aria-pressed={ownerMode===x} onClick={()=>setOwnerMode(x)}>{x}</button>)}</div><label><span>اسم صاحب الوقف</span><input value={owner} onChange={e=>setOwner(e.target.value)} required/></label>{type==="gift"&&<><label><span>اسم المرسل — اختياري</span><input value={sender} onChange={e=>setSender(e.target.value)}/></label><label><span>المناسبة أو النية</span><select value={occasion} onChange={e=>setOccasion(e.target.value)}><option>وقف عام</option><option>عن الوالدين</option><option>عن متوفى</option><option>مناسبة خاصة</option></select></label></>}<label><span>الإهداء أو النية</span><textarea value={dedication} maxLength={180} onChange={e=>setDedication(e.target.value.slice(0,180))}/><small>{dedication.length}/180</small></label>{!owner.trim()&&<small className="field-error">اسم صاحب الوقف مطلوب لمعاينة الشهادة.</small>}</fieldset><Button type="button" variant="outline" onClick={()=>setStep(4)}>معاينة الشهادة</Button></div>
 <div className={step===4?"w-step active":"w-step"}>{certificate}<Button type="button" variant="outline" onClick={()=>setStep(5)}>عرض الملخص</Button></div>
 <div className={step===5?"w-step active":"w-step"}><div className="w-summary" aria-live="polite"><span>ملخص الوقف</span><dl><div><dt>النوع</dt><dd>{summary.type}</dd></div><div><dt>المشروع</dt><dd>{summary.project}</dd></div><div><dt>صاحب الوقف</dt><dd>{summary.owner}</dd></div><div><dt>المبلغ</dt><dd>{summary.amount}</dd></div>{type==="project"&&<div><dt>النطاق</dt><dd>{scope}</dd></div>}</dl><p>لا يوجد عائد مالي للمتبرع، والشهادة الحالية Preview فقط.</p></div><Button fullWidth onClick={addBasket}>أضف الوقف إلى سلة العطاء</Button><Button fullWidth variant="outline" onClick={checkout}>أنشئ وقفًا</Button></div>
 <section className="w-meter"><header><span>مقياس المساهمة الوقفية</span><p>نوع الوحدة وقيمتها يحتاجان اعتماد الإدارة.</p></header><div>{[1,3,10].map(v=><button key={v} className={units===v?"is-selected":""} aria-pressed={units===v} onClick={()=>setUnits(v)}>{v} وحدة</button>)}<label><span>مخصص</span><input type="number" min={1} value={units} onChange={e=>setUnits(Math.max(1,Number(e.target.value)||1))}/></label></div></section>{message&&<p className="w-message" role="status">{message}</p>}</div>;
 return <><section id="waqf-builder" className="w-builder" aria-labelledby="w-builder-title"><header><span>أداة Frontend تجريبية</span><h2 id="w-builder-title">اختر طريقة مساهمتك الوقفية</h2><p>لا تُعرض أسعار أو وحدات كحقائق ما لم تكن معتمدة.</p></header>{builder}</section><div className="w-mobile-bar"><div><small>أنشئ وقفًا</small><strong>{typeLabels[type]} · {selectedProject?.title||"مشروع وقفي"}</strong></div><button ref={triggerRef} onClick={()=>setSheet(true)}>ابدأ</button></div>{sheet&&<div className="w-layer"><button className="w-backdrop" aria-label="إغلاق" onClick={()=>setSheet(false)}/><aside ref={sheetRef} className="w-sheet" role="dialog" aria-modal="true" aria-labelledby="w-sheet-title"><header><h2 id="w-sheet-title">إنشاء وقف</h2><button onClick={()=>setSheet(false)} aria-label="إغلاق">×</button></header>{builder}</aside></div>}<div className={toast?"toast is-visible":"toast"} role="status" aria-live="polite">تمت إضافة الوقف إلى السلة</div></>;
}
